### ISSUE TITLE
Animation under slider section works only once

### ISSUE THREAD

**Issue by Andrejamtv** [soflyy/oxygen-bugs-and-features#2130] opened 2021-04-27 09:19 UTC
Hello everyone, I'm reporting a bug.
Below the section where the slider is, the animation in the other section works only once, when the page is refreshed the animated text disappears. When I move the mentioned section with animated text above the section with the slider, everything works normally.
Is there a solution to solve this problem?

thanks

**Comment by Spellhammer** [comment] 2021-04-27 12:53
Closing due to lack of reproduction steps and/or Sandbox link.

@Andrejamtv Please send us a ticket via https://oxygenbuilder.com/support and we'll be glad to assist.

**Closed by Spellhammer** 2021-04-27 12:53 UTC
Labels: bug
