### ISSUE TITLE
2.4RC2 - Conditional UI problem

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#379] opened 2019-07-04 03:40 UTC
**Describe the bug**
Extra close button appearing above conditional settings causing an odd rectangle to also appear.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, [one click login](http://talented-octopus.w6.wpsandbox.pro?upass=u9D6tKAwo2M8) 

It wasn't happening in RC1.

**Screenshots**
<img width="1000" alt="Screen Shot 2019-07-04 at 1 37 02 pm" src="https://user-images.githubusercontent.com/43051571/60638321-4188a000-9e61-11e9-85e6-8bfccb468d15.png">

**Comment by wplit** [comment] 2019-07-04 04:00
Ok, I've just checked and it's always been there. I was working on a different screen resolution and hadn't noticed it. Still, it probably doesn't need to be there as there is already a close icon in the top right.

**Comment by louisreingold** [comment] 2019-07-04 06:51
Good catch - it's not supposed to be there. We never noticed it because I guess it must have been behind the modal on all the screen resolutions we use. We're not doing an RC3 though so this will wait for the next point release.

**Comment by adrien-robert** [comment] 2019-07-08 08:03
I can confirm the issue on a 2560x1440 monitor

![image](https://user-images.githubusercontent.com/4320990/60793243-95e49600-a167-11e9-9b35-64f22391e5eb.png)

**Comment by KittenCodes** [comment] 2020-01-01 16:02
This is fixed in the latest release of Oxygen.

**Closed by KittenCodes** 2020-01-01 16:02 UTC
Labels: bug
