### ISSUE TITLE
Remove the Google Fonts from the font dropdown in the builder if they have been deactivated

### ISSUE THREAD

**Issue by realmalikov** [soflyy/oxygen-bugs-and-features#3470] opened 2023-12-16 16:55 UTC
Please remove the Google Fonts from the font dropdown in the builder if they have been deactivated. I don't need to see them if I don't want to use them anyway.

Thank you!

**Comment by Kpudlo** [comment] 2023-12-19 18:09
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/236

**Closed by Kpudlo** 2023-12-19 18:09 UTC
Labels: enhancement
