### ISSUE TITLE
Oxygen doesn't work with Yoast SEO plugin's readability and content analysis

### ISSUE THREAD

**Issue by JackGraal** [soflyy/oxygen-bugs-and-features#516] opened 2019-09-02 08:53 UTC
**Describe the bug**
*The content and readability analysis stops working as soon as Oxygen is activated. It says there's not enough content.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes: [here's the link](http://brainy-gecko.w6.wpsandbox.pro/2017/03/09/far-far-away/).*

**To Reproduce**
1. Install and activate Yoast SEO Plugin
2. Install and activate Oxygen
3. Add an example post with some content and publish it.

**Expected behavior**
*Yoast should be able to analyse the content and readability and show some suggestions.*

**What actually happens**
*Content analysis and readabiliy features in Yoast Meta Box shows that there's not enough content - no matter how much content you write. It just doesn't see any content to analyse because of Oxygen.*

**Screenshots**
![Screenshot of Edit Post ‹ Sandbox — WordPress](https://user-images.githubusercontent.com/20714392/64102123-8f415c00-cd6f-11e9-9fa6-e924528defc7.jpg)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Chrome
 - Oxygen Version: 2.4.1

**Comment by Martin-1** [comment] 2019-09-02 10:01
+1

**Comment by KittenCodes** [comment] 2019-09-02 10:37
@JackGraal Unfortunately this is a known issue when using Yoast with Oxygen. The problem is that when you're using a template to render your post content, then the content can't be analysed correctly. However, if you edit the post content directly (don't use a template and click "Edit with Oxygen" directly on the post page) and then insert the content dynamically then it will be analysed.

Please note that the lack of indicators shouldn't impact the SEO of your site.

**Comment by JackGraal** [comment] 2019-09-02 10:59
@KittenCodes Well, if it's just standard post content it shouldn't need anything from Oxygen to be analysed by Yoast SEO in the backend editor. It just doesn't make sense. Oxygen seems to use the post content only when it's outputed in the front end. Why does it block something in the admin dashboard?

**Comment by JackGraal** [comment] 2019-09-23 06:44
Is there some progress with this issue? 

Yoast has a guide for plugin developers to fix this issue: https://github.com/Yoast/YoastSEO.js/blob/master/docs/Customization.md

**Comment by Jaegowah** [comment] 2019-11-09 19:27
Would be great if this gets fixed - thank you dear developers!

**Comment by eMiz0rz** [comment] 2019-11-26 15:24
Semrush SEO Writing Assistant isn't working (probably for the same reason) either. How come Yoast is mentioned on the frontpage under "built-in support" when it clearly isn't? https://oxygenbuilder.com/tour/performance/

Don't get me wrong; I really **love** the product, so I would be really sad if I had to move away from oxygen builder when SEO tools do not work.

Or... is there a workaround?

**Comment by Miroslav1993** [comment] 2019-12-16 09:20
Can we get an answer or workaround until this is fixed? Clients have non-functional Yoast on any site using Oxygen.

**Comment by KittenCodes** [comment] 2019-12-29 18:04
@Miroslav1993 

> Can we get an answer or workaround until this is fixed? Clients have non-functional Yoast on any site using Oxygen.

Edit the post content directly (don't use a template and click "Edit with Oxygen" directly on the post page) and then insert the content dynamically then it will be analysed.

**Comment by jrc2** [comment] 2020-01-03 02:44
@KittenCodes I built a site for a client and all pages were edited directly in Gutenberg and displayed using Inner Content, and Yoast still showed 0 content

**Comment by srikat** [comment] 2020-02-02 02:38
Temp workaround/fix: https://wpdevdesign.com/fix-for-yoast-seo-in-oxygen/.

**Comment by Deleyna** [comment] 2020-03-05 08:33
> 
> 
> Temp workaround/fix: https://wpdevdesign.com/fix-for-yoast-seo-in-oxygen/.
> 
> Update: Created a plugin > https://github.com/srikat/wpdevdesign-oxygen-yoast-seo.

THANK YOU for this!!!

**Comment by sunnyt7** [comment] 2020-05-05 19:19
Ran into this today. Thanks for the plugin @srikat!

This should really be fixed in Oxygen core though.

**Comment by fahimanwer** [comment] 2020-06-30 12:49
What about the modules offered by yoast like howto schema and faq schema

**Comment by harryfear** [comment] 2020-07-30 18:42
Has this been solved in vanilla Oxygen yet, by v. 3.3?

**Comment by jportiz55** [comment] 2020-07-30 19:51
@harryfear, nope.
But this plugin fixed the problem.

**Comment by KittenCodes** [comment] 2020-10-17 10:42
Fixed in v3.6 Beta.

**Closed by KittenCodes** 2020-10-17 10:42 UTC
Labels: bug, confirmed bug
