### ISSUE TITLE
Header template not 'displaying' after All in One WP migration

### ISSUE THREAD

**Issue by winwinwebsites** [soflyy/oxygen-bugs-and-features#606] opened 2019-10-07 11:01 UTC
**Describe the bug**
After using All In One WP Migration on Oxygen V3, the header and footer template 'disappeared' on the migration.

Changing the template priority setting to 1 or higher makes it reappear as normal.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Expected behavior**
Website imports exactly without having to change the priority settings

**What actually happens**
Website imports fine, but without the header or footer showing.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
 - Oxygen Version 3.0.1

**Comment by alriksson** [comment] 2019-10-14 18:48
Have the same issue no matter which migration tool :) Tried https://wordpress.org/plugins/wpvivid-backuprestore/ and issue persist.

Reassign shortcodes and regenerate CSS. I also have the issue with flushing cache cause the style sheet to break. Where I have to disable and enable.

**Comment by KittenCodes** [comment] 2019-12-29 13:46
@winwinwebsites I'm not able to reproduce this issue. If you're still encountering this issue, please email support@oxygenbuilder.com so that we can take a look at your site.

**Closed by KittenCodes** 2019-12-29 13:46 UTC
Labels: bug

**Comment by ivandurst** [comment] 2020-04-29 13:37
I have the same issue. Export/import with both backdraft plus and Local Flywheel app

**Comment by KittenCodes** [comment] 2020-04-29 13:39
After migrating the site, please follow these steps:

- Save your permalinks twice via Settings > Permalinks
- Resign your shortcodes via Oxygen > Settings > Shortcodes
- Regenerate your CSS cache via Oxygen > Settings > CSS Cache

​You may also need to open each template in the admin area and click the Update button on the right-hand side, but I've only found that to be required on a handful of sites.
​
​If you have any caching plugins installed, you will also need to clear the caches.
