### ISSUE TITLE
Bugs: Cannot Select Apply Templates in WP 6.7

### ISSUE THREAD

**Issue by kokohcokisiregar** [soflyy/oxygen-bugs-and-features#3593] opened 2024-11-13 12:45 UTC
![466669042_2860897990742003_339542709364353928_n](https://github.com/user-attachments/assets/ed80e67c-ad50-494f-a433-9aa065c1bce7)

on WP 6.7 cannot open/select the apply templates option, when rollback to WP 6.6.2 is works again.

**Comment by Kpudlo** [comment] 2024-11-13 13:10
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3592

**Closed by Kpudlo** 2024-11-13 13:10 UTC
Labels: bug
