### ISSUE TITLE
Easy Posts Random Feature

### ISSUE THREAD

**Issue by WebsiteService360** [soflyy/oxygen-bugs-and-features#1718] opened 2020-11-17 00:37 UTC
**Describe the feature you'd like to see included in Oxygen.**
I would like a feature added to the Easy Posts Custom WP Query section. The feature is to offer a random setting. While I've see posts talking about setting that up in the manual section, I have yet to see it work properly. I have, however, made it work properly in the Custom setting by modifying the easy-posts.class.php file.

**What are the use cases for this feature?**
The ability to easily add randomized posts. The example I used it for was to display a single random tip from a collection of tips setup in a custom post type.

How to make it work?
Find this block in easy-posts.class.php

                                    <div class="oxygen-select-box-option"
                                        ng-click="$parent.iframeScope.setOptionModel('query_order_by','menu_order');"
                                        title="<?php _e("Set order by", "oxygen"); ?>">
                                        <?php _e("Menu Order", "oxygen"); ?>
                                    </div>
And add the following block behind it.

                                    <div class="oxygen-select-box-option"
                                        ng-click="$parent.iframeScope.setOptionModel('query_order_by','rand');"
                                        title="<?php _e("Set order by", "oxygen"); ?>">
                                        <?php _e("Random", "oxygen"); ?>
                                    </div>
Works like a charm until Oxygen updates again.

**Comment by KittenCodes** [comment] 2020-12-31 17:46
Duplicate of #1003

**Closed by KittenCodes** 2020-12-31 17:46 UTC
Labels: Element - Easy Posts/Repeater, enhancement
