### ISSUE TITLE
Re-order Global Colors

### ISSUE THREAD

**Issue by anrouk** [soflyy/oxygen-bugs-and-features#3224] opened 2023-02-01 13:37 UTC
**Describe the feature you'd like to see included in Oxygen.**
Currently, I don't see away to re-organise or re-order the Global colors.  This would make selecting colors from within an element a lot easier to manage. 

**What are the use cases for this feature?**
As a website evolves, sometime the global palette also expands and over time becomes quite disorganised.

**Examples of this feature or functionality.**
If within Settings/Colors/Gobal Colors - there was away drag-and-drop the individual colors, which is reflected in the Global Colors of the Color picker, would be so helpful.

**Comment by Kpudlo** [comment] 2023-02-01 16:30
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/84

**Closed by Kpudlo** 2023-02-01 16:30 UTC
Labels: enhancement
