### ISSUE TITLE
Wordpress 5.5 (Tinymce) and oxygen Gutenberg

### ISSUE THREAD

**Issue by scriptaimago** [soflyy/oxygen-bugs-and-features#1446] opened 2020-08-18 12:45 UTC
With the introduction of wordpress 5.5, all rich_text elements inside the Oxygen Gutenberg blocks do not work.
Once inserted in a page or article, when you click them to edit text, they appear white.
On the console log of the browser appears an error related to Tinymce.
When you roll back to wordpress 5.4 (I did), everything works again, just as it should.

I hope you can get it fixed.
All the best.
Lorenzo

**Comment by greenfrog111** [comment] 2020-08-18 13:21
I've encountered the same problem, although I hadn't identified the WP upgrade to 5.5 as the cause.

**Comment by Spellhammer** [comment] 2020-08-18 16:26
This should be fixed in 3.5 RC 1, which is now available at https://oxygenbuilder.com/portal for existing customers.

**Closed by Spellhammer** 2020-08-18 16:26 UTC
Labels: bug
