### ISSUE TITLE
oxygen +wpml

### ISSUE THREAD

**Issue by max0boy** [soflyy/oxygen-bugs-and-features#2089] opened 2021-04-12 13:24 UTC
1. The main page is assigned
2. wpml is configured so that languages are displayed in this form (/uk/ *, /ru/ *. The main language  EN on the domain.
When opening the main page with a logged in, part of the content is not shown and the following error is displayed in the console:
https://www.dropbox.com/s/j84w1n8reuyz50a/oxy1.png?dl=0
https://www.dropbox.com/s/cxjc4ycsqy1qnnq/oxy2.png?dl=0
so in all languages of the main page

If you are not logged in or in incognito everything works out ok

If I follow the url of the page to the straight line, then everything is ok
https://www.dropbox.com/s/2dotoy9qswk0rwx/oxy3.png?dl=0

**Comment by Kpudlo** [comment] 2023-04-26 13:29
Duplicate of #938

**Closed by Kpudlo** 2023-04-26 13:29 UTC
Labels: Integration - Multilingual
