### ISSUE TITLE
div element background video

### ISSUE THREAD

**Issue by zaheen** [soflyy/oxygen-bugs-and-features#1018] opened 2020-04-13 16:24 UTC
**Video background for div elements**
*I would like to request to add background video feature like section background video.*

**to display video on div element like section**
*It's very cool video background on sections, so I would like to get same feature to div elements*

**Comment by Kpudlo** [comment] 2023-02-23 13:24
Closing this one as it is a duplicate of #1826

**Closed by Kpudlo** 2023-02-23 13:24 UTC
Labels: enhancement, Element - Section/Div/Columns, UI - Background Image/Video/Gradient
