### ISSUE TITLE
Oxygen 4 Alpha Var in Fontsize

### ISSUE THREAD

**Issue by OliverOPV** [soflyy/oxygen-bugs-and-features#2631] opened 2021-12-29 15:17 UTC
Everytime I try to enter a variable in to fontsize ist adds a value of 50 automatically.

**Comment by Spellhammer** [comment] 2021-12-29 15:26
Thanks for the report!

Closing as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2611.

**Closed by Spellhammer** 2021-12-29 15:26 UTC
Labels: bug
