### ISSUE TITLE
Twitter Logo

### ISSUE THREAD

**Issue by Cheryl-neco** [soflyy/oxygen-bugs-and-features#3394] opened 2023-09-11 19:33 UTC
Please update the social_icons helper to include the new "X" logo for Twitter in addition to or instead of the original bird icon.

**Comment by Kpudlo** [comment] 2023-09-12 23:58
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3376

**Closed by Kpudlo** 2023-09-12 23:58 UTC
Labels: enhancement
