### ISSUE TITLE
WooCommerce 5.5.1 issue with Search

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#2309] opened 2021-07-21 00:41 UTC
Ever since WooCommerce v5.5.1, when you search for a product (e.g. domain.com/?s=shirt&post_type=product), instead of seeing the correct results, all you get is a blank white page.

This works fine on older versions of WooCommerce, but NOT in the latest update which is WooCommerce 5.5.1

Nothing comes up  in my logs.

Here are some more reports of this issue:
https://www.facebook.com/groups/1626639680763454/posts/4130354883725242
https://diviengine.com/woocommerce-5-5-1-issue-with-divi-search/
https://github.com/woocommerce/woocommerce/issues/30298

**Comment by KittenCodes** [comment] 2021-07-23 14:32
This is caused by the latest WooCommerce update and will need to be fixed by the WooCommerce team themselves. It seems that it's affecting lots of sites - not just Oxygen sites.

There's more information on the WooCommerce GitHub here: https://github.com/woocommerce/woocommerce/issues/30298.

Please try the fix from the below URL:

https://diviengine.com/woocommerce-5-5-1-issue-with-divi-search/

The fix requires you to download the file from the above link and use that file in place of the existing \wp-content\plugins\woocommerce\includes\class-wc-query.php file.

**Closed by KittenCodes** 2021-07-23 14:32 UTC
Labels: bug

**Comment by shmaltz** [comment] 2021-07-25 04:35
Confirmed fixed in Woo v5.5.2
