### ISSUE TITLE
Adding align text in the main tab

### ISSUE THREAD

**Issue by Dinophox** [soflyy/oxygen-bugs-and-features#3088] opened 2022-09-26 06:57 UTC
This is a very simple request where many people and myself would like to have aligned text in the main tab, photo attached.

**What are the use cases for this feature?**
3 fewer clicks to align the text where wanted. It is a great UX.

![Screenshot 2022-09-25 at 14 22 36](https://user-images.githubusercontent.com/28341951/192212046-952456b0-2921-42e5-8897-272aa23f97c5.jpg)

**Comment by Kpudlo** [comment] 2022-09-27 15:18
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/488

**Closed by Kpudlo** 2022-09-27 15:18 UTC
Labels: enhancement
