### ISSUE TITLE
Animations not working and z-index rules not being followed

### ISSUE THREAD

**Issue by axp32** [soflyy/oxygen-bugs-and-features#3032] opened 2022-08-04 20:35 UTC
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

https://oxygen-qz8k4fm885bnl.oxygen-demo.qsandbox.me/sample-page/
https://oxygen-qz8k4fm885bnl.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true
**Describe the bug**
*A clear and concise description of what the bug is.*

A section with a slider element in it does not fire the animation to slide down as well as being on top in the z index(should be under the previous slide.  However, animation does fire when refreshing the page in the same place where the element should end up.
also happens with elements that do not have slider elements. If you tried to do the slide-down animation on my  "Contact My Consultants" element the same thing happens, the element gets stuck in the starting position.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

(https://oxygen-qz8k4fm885bnl.oxygen-demo.qsandbox.me/sample-page/
(https://oxygen-qz8k4fm885bnl.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment] 2022-08-05 12:53
As a quick workaround, add this JavaScript to the JS editor of a Code Block on the page or template:

```js
setTimeout(() => {AOS.refresh();}, 500);
```

**Comment by Spellhammer** [comment] 2022-08-05 12:54
Marking this as under investigation until we're able to reproduce internally.

**Comment by Spellhammer** [comment] 2022-08-30 16:32
After further investigation, this looks to be a configuration issue, not a bug. Closing.

**Closed by Spellhammer** 2022-08-30 16:32 UTC
Labels: bug, under investigation
