### ISSUE TITLE
Metabox cloneable group and repeater issues

### ISSUE THREAD

**Issue by studiouau** [soflyy/oxygen-bugs-and-features#2552] opened 2021-12-02 16:52 UTC
Hi,

I think there are some issues with the new integration with metabox cloneable group inside a repeater.

http://crowded-wallaby.w6.wpsandbox.pro/image-advanced-field/
It seems that image advanced field inside a repeater doesn't work.

http://crowded-wallaby.w6.wpsandbox.pro/image-field/
Image field show up only thumbnails image.

http://crowded-wallaby.w6.wpsandbox.pro/date-field/?ct_builder=true
There's no way to change date format.

**Comment by KittenCodes** [comment] 2021-12-04 20:06
> Image field show up only thumbnails image.

Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2546.

> There's no way to change date format

Thank you for letting us know about this. I've replicated the issue and reported it internally.

**Comment by studiouau** [comment] 2021-12-04 22:59
Hi Phe, thank you for your reply.
What about image advanced field? Do you confirme the bug?

**Comment by KittenCodes** [comment] 2021-12-05 08:39
> What about image advanced field? Do you confirme the bug?

I was able to retrieve the thumbnail using an Image Advanced field. If it's not working at all for you, please could you replicate this on our Sandbox site and send me a login?

You can create a Sandbox site here: https://oxygenbuilder.com/try.

**Comment by studiouau** [comment] 2021-12-10 11:53
Hi Phe, sorry for the late reply.

No, it seems that the advanced field inside a repeater is not working. It does not show any images.
I think most of the problems are related to group <-> repeater.

![image](https://user-images.githubusercontent.com/56966443/145569776-27c38736-2e09-4444-858e-6d1e87470c40.png)

![image](https://user-images.githubusercontent.com/56966443/145569687-57558a28-a27d-4b56-9de7-f5aee1483e70.png)

Here the demo.
http://stormy-gentoo.w6.wpsandbox.pro/image-advanced-field-inside-a-repeater/

I hope it helps.

Thank you

**Comment by KittenCodes** [comment] 2021-12-14 11:37
Thanks @studiouau. I've reported this internally.

**Closed by KittenCodes** 2021-12-14 11:37 UTC
Labels: bug, confirmed bug
