### ISSUE TITLE
ACF Integration creates wrong mailto syntax

### ISSUE THREAD

**Issue by andreasritter** [soflyy/oxygen-bugs-and-features#898] opened 2020-03-14 20:25 UTC
**Describe the bug**
Using an ACF E-Mail field and trying to insert the address as link into oxygen creates a link with "mailto://email@email.com" it should be "mailto:email@email.com". There are // after mailto: that should not be there.

**To Reproduce**
It' quicker to write where to fix the problem:
FILE oxygen-acf-integration.php
METHOD "acf_url_handler"
CASE "email" should be: $output = 'mailto:' . ( is_array( $field["value"] ) ? $field["value"][0] : $field["value"] );

**Expected behavior**
"mailto:email@email.com"
$output = 'mailto:' . ( is_array( $field["value"] ) ? $field["value"][0] : $field["value"] );

**What actually happens**
"mailto://email@email.com"
$output = 'mailto://' . ( is_array( $field["value"] ) ? $field["value"][0] : $field["value"] );

**Desktop (please complete the following information):**
- OS: irrelevant
 - Browser irrelevant
 - Oxygen Version 3.2

**Comment by mhennemann** [comment] 2020-10-15 11:19
hello. is this bug solved ? I have the same issue at the moment . thanks

**Comment by studiouau** [comment] 2021-01-13 11:57
OUCH.

Same here, anyone has a fix?

**Comment by chrizoo** [comment] 2021-01-21 22:09
my workaround:

URL - data - PHP Function Return value
and then in Function Name: get_field
and in Arguments: e-mail

I added mailto: before the data and it worked.

**Comment by sublimegd** [comment] 2021-02-11 04:57
I am experiencing the same problem, and I can't for the life of me figure it out. :(
The URL is currently:
mailto:[oxygen ct_sign_sha256='7211da8299ad707e539ab005d152418db9e203254773ece85991a949ad380769' data='custom_acf_link' settings_path='email_address' ]

I have tried chrizoo's workaround above & it still doesn't work. 

Does anyone else have any ideas?

**Comment by KittenCodes** [comment] 2021-04-29 14:15
Fixed in v3.8 Beta 1.

**Closed by KittenCodes** 2021-04-29 14:15 UTC
Labels: bug, confirmed bug

**Comment by AlkoKod** [comment] 2023-01-02 22:10
It was working, but is doesn't anymore with latest Oxygen 4.3. It adds: mailto:http://email@domain.com ... same with tel: links. How to fix this? @KittenCodes

**Comment by Kpudlo** [comment] 2023-01-07 12:59
Hello @AlkoKod, 

I couldn't recreate the issue on a sandbox site. Please provide the steps you are taking to see the issue or create a sandbox with the issue (https://oxygenbuilder.com/try/) and send a link to the sandbox.

**Comment by Kpudlo** [comment] 2023-02-09 12:16
Hello @AlkoKod, 

I appreciate your patience. I've tried to replicate this setup, but everything works for me when using a Text Link in an ACF Repeater field. For reference, the ACF field is an email field: https://www.loom.com/share/d505decfb91c4879ae8cf9b2af7426bc. 

If you still have issues with this, please try and recreate this on a Sandbox site and provide a link to the Sandbox so we can look into it more.

**Comment by Green-Zero-Development** [comment] 2024-03-18 20:54
I've run into this problem in a project I'm working on rn.

I ended up using a Code Box as a workaround - but I recreated this in sandbox for exploration:
https://oxygen-q8b669ncd2zxl.oxygen-demo.qsandbox.org/

Further details:
- The ACF field is "Text" type (as far as I know, there's no phone type).
- The "tel:" is manually typed before the Oxygen shortcode in the URL box of the "Link Wrapper" element. I didn't see any other way to create a tel: link using the Link Wrapper. I also did the same with a "Text Link" element.

**Comment by AlkoKod** [comment] 2024-03-19 20:05
@Green-Zero-Development good that someone have a time to create the sandbox because this bug is so annoying and I have no clue why it is closed.

**Comment by Kpudlo** [comment] 2024-03-20 12:36
Hello @Green-Zero-Development, 

Thank you for the information. We've been able to confirm the issue you are seeing. 

As this is a separate issue from the one originally posted, we've created a new bug report for this via #3519. 

Additionally, a workaround until the issue is addressed is to use the Meta/Custom Field Data Point instead of the ACF Data Point or the Code Block solution you've found.
