### ISSUE TITLE
Add width and height attributte in images

### ISSUE THREAD

**Issue by flabernardez** [soflyy/oxygen-bugs-and-features#2317] opened 2021-07-23 07:25 UTC
Add width and height attributte in images automatically when the sizes are filled in Primary tab.

Now I have to do that twice: one on Primary Tab and another when in the Advanced tab when I attach atributtes in that element.

That will be awesome to performance issues.

Thanks!

**Comment by jornessim** [comment] 2021-12-28 18:06
+1

**Comment by MattHag** [comment] 2022-11-03 11:01
That's a great suggestion, that I miss badly in my fight to minimize CLS.

I expect something as basic as this to be handled by Oxygen.

**Comment by MattHag** [comment] 2022-11-03 11:05
This issue is also a duplicate of the often requested
https://github.com/soflyy/oxygen-bugs-and-features/issues/1752

There are 4 issues requests for that, that need to be combined to calculate the urgency/like score for that.

**Comment by Kpudlo** [comment] 2022-11-09 22:43
duplicate of #1752

**Closed by Kpudlo** 2022-11-09 22:43 UTC
Labels: enhancement, Element - Image
