### ISSUE TITLE
Add more native alignment options to Oxygen Gutenberg Blocks

### ISSUE THREAD

**Issue by AnthonyBrowneCreative** [soflyy/oxygen-bugs-and-features#3349] opened 2023-07-10 18:35 UTC
**Add more alignment options to Oxygen Gutenberg Blocks**

*When adding custom-made Oxygen Gutenberg blocks to the default WP Gutenberg editor, the block takes up the full width, regardless of its inherent styling*

This is extremely frustrating as it makes editing in Gutenberg cumbersome. This is especially true when the block uses an SVG image as the image enlarges to fill 100% of the editor width and the same proportional height.

For instance, I have made a custom pull quote Oxygen Block for one of my client projects. The image is a quote icon in SVG format which has been styled to be an actual size of 120px wide, and the entire card is no wider than 960px, sitting comfortably in the centre of the parent container in the rendered HTML. When the block is added to the Gutenberg editor, it takes up far too much space, and there are no alignment options other than 'None', or 'Full width’ to control it.

The only way to reduce the width of the block is to hack the oxygen-gutenberg.js (as per the instructions from @yankiara in the post titled, ‘[Oxygen blocks are all fullwidth in Gutenberg Editor #743](https://github.com/soflyy/oxygen-bugs-and-features/issues/743)’). This person's method works, temporarily, but it's not ideal as the js code needs to be re-hacked after any future updates. Furthermore, since I last tried this in Oxygen 4.4.2, I've been experiencing frequent data loss in my Oxygen pages and templates, so I have been forced to rest the plugin to the default state.

Therefore, to help your users build editable pages in the Guttenberg editor more effectively, please can you add the option to centre the oxygen block (which is more effective for allowing clients to edit blocks that are intended to take up less than 100% of the container width), as well as being able to set the block full width (which is more effective for allowing clients to edit whole pages).

Thanks.

Anthony.

![oxy-custom-pull-quote-block](https://github.com/soflyy/oxygen-bugs-and-features/assets/74543030/1b54120e-6df3-4d62-96ea-30a118ead49a)

![oxy-custom-pull-quote-block-html](https://github.com/soflyy/oxygen-bugs-and-features/assets/74543030/dc18197c-b0eb-45e3-845e-8b0d8d427222)

**Comment by Kpudlo** [comment] 2023-08-18 22:07
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/743

**Closed by Kpudlo** 2023-08-18 22:07 UTC
Labels: enhancement
