### ISSUE TITLE
Please add a 'Select All' checkbox in the re-sign shortcodes section.

### ISSUE THREAD

**Issue by Phease69** [soflyy/oxygen-bugs-and-features#3012] opened 2022-07-20 11:00 UTC
When I have to re-sign shortcodes, for example after pulling a site into LOCAL from my remote host, I have to manually select the post types from the list. I have about 20. It would be helpful if there were a little checkbox at the top to select all of them rather than having to manually click them all! 

Its a small frustration, but also I am sure a very easy update too! :-) 

Cheers

**Comment by guyinpv** [comment] 2023-01-16 00:17
Duplicate of #429

**Closed** 2023-01-20 20:01 UTC
Labels: enhancement
