### ISSUE TITLE
Site still scrolls while modal is open

### ISSUE THREAD

**Issue by greenisland-tim** [soflyy/oxygen-bugs-and-features#279] opened 2019-05-03 20:38 UTC
**Describe the bug**
When a modal is open, the site beneath it still scrolls. Typically a modal will lock the site by adding overflow:hidden. The current behavior is problematic if you have a modal with content that may extend beyond the viewport (e.g. contact form on mobile) because you can't scroll to access it.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
2.3 not installed

**To Reproduce**
1. Add a modal
2. Open modal on live site
3. Scroll mouse to see behavior

**Expected behavior**
Site in the background should "lock" when modal opens, and unlock when modal is closed.

**What actually happens**
Site in background remains scrollable

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [Mac OS]
 - Browser [Chrome]
 - Oxygen Version [e.g. 2.3 RC1]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by srikat** [comment] 2019-05-07 11:55
Here's a demo page where the problem can be seen: https://oxymodal.demo.site/before/

and here's the attempted fix with a bit of custom CSS and JS: https://oxymodal.demo.site/after/

**Comment by greenisland-tim** [comment] 2019-05-07 12:14
Thanks Sridhar. I was able to do it with a couple of lines of JS which seem to work without any new css. Your example is perfect...it doesn't take too many fields in a form to push the modal outside the window. Not really a bug, just non-traditional behavior for a modal.

//* MODAL SCROLL FIX
$('#modal-open').click(function(){
	$('body').css("overflow", "hidden");
});
$('.oxy-close-modal, .oxy-modal-backdrop').click(function(){
	$('body').css("overflow", "scroll");
});

**Comment by srikat** [comment] 2019-05-07 12:26
@greenisland-tim I am indeed using your JS on my "after" page.

```
(function($) {
'use strict';
  
	$('.modal-trigger').click(function(){
		$('body').css("overflow", "hidden");
	});

	$('.oxy-close-modal, .oxy-modal-backdrop').click(function(){
		$('body').css("overflow", "scroll");
	});

}(jQuery));
```

I have created a copy of the "after" page here: https://oxymodal.demo.site/after-2/. This does not have the custom CSS and as a result, the top portion (that shows the form name) does not appear in my phone. Can you check and confirm?

This is the CSS that is additionally added to in "after" page:

```
.oxy-modal-backdrop .ct-modal {
  	overflow-y: auto;
	max-height: calc(100vh - 40px);
}

@media only screen and (max-width: 768px) {
  
	.oxy-modal-backdrop .ct-modal {
		margin-top: 60px;
	}

}
```

**Comment by greenisland-tim** [comment] 2019-05-07 12:48
I can confirm the modal in /after-2/ overflows top and bottom (on my 13" laptop) and doesn't scroll in either direction. 

I had already assigned a custom height to the modal almost identical to yours (using calc(100vh - XX)), and assigned overflow:scroll in the builder, so our solutions were essentially identical.

My dev site is here, click the Explore button in upper left: https://gicore.flywheelsites.com/

**Comment by srikat** [comment] 2019-05-08 04:56
https://wpdevdesign.com/fixing-the-modal-issue-in-oxygen-2-3/

**Comment by qriouslad** [comment] 2019-05-18 06:58
I am solving this by mimicing Bootstrap v3's modal behaviour:
https://getbootstrap.com/docs/3.3/javascript/#modals

In Customizer, add the following CSS:

```
.oxy-modal-backdrop.live {
	display: block !important;
	position: fixed;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	overflow-x: hidden;
	overflow-y: auto;
}

.ct-modal {
	margin: 20px auto;
}
```

2. And then, on each page where you have problematic modals, add the following code block:

```
(function($) {
'use strict';

        $('.oxy-close-modal, .oxy-modal-backdrop').click(function(){
                $('.oxy-modal-backdrop.live').removeClass("live");
                oxyCloseModal();
        });

}(jQuery));
```

The 'root' cause of the issue in the first place is Oxygen's use of "display: flex" for the modal wrapper div. Changing it to "display: block" solved it for me, though I needed to use "!important" to override Oxygen's default behaviour, and then removing this on clicking close modal / modal background via 'removeClass("live")'.

**Comment by ollycowan** [comment] 2019-06-21 09:51
Will this be fixed in 2.4? It seems the issue is still present.

**Comment by ayhanmalkoc** [comment] 2019-09-21 17:18
+1

**Comment by Deanphillips** [comment] 2019-10-09 02:54
+1

**Comment by wplit** [comment] 2019-11-14 05:10
Another solution for modals being cut off (and not scrollable) on small screens...

As pointed out in a comment above, the problem is in the flex settings of the .oxy-modal-backdrop. But I don't think the solution is to make it display: block. Then we lose the ability to position the modals correctly with the built in controls.

Another way I found is to keep the display: flex on the container '.oxy-modal-backdrop' but instead of allowing the alignment CSS on the container control the modals position, we can use margins on the modal itself to override that.

The difference being that margin: autos when applied to flex children don't have the same problem of falling off the screen, the top of the modal will never go above the top of the viewport and they are scrollable by default.

```
.oxy-modal-backdrop:not(.bottom_left):not(.upper_left):not(.bottom_right):not(.upper_right):not(.bottom):not(.top):not(.right):not(.left) .ct-modal {
  margin: auto;
}

.oxy-modal-backdrop.bottom_left .ct-modal {
  margin-right: auto;
  margin-top: auto;
}

.oxy-modal-backdrop.upper_left .ct-modal {
  margin-right: auto;
  margin-bottom: auto;
}

.oxy-modal-backdrop.bottom_right .ct-modal {
  margin-left: auto;
  margin-top: auto;
}

.oxy-modal-backdrop.upper_right .ct-modal {
  margin-left: auto;
  margin-bottom: auto;
}

.oxy-modal-backdrop.top .ct-modal {
  margin-bottom: auto;
}

.oxy-modal-backdrop.left .ct-modal {
  margin-right: auto;
}

.oxy-modal-backdrop.bottom .ct-modal {
  margin-top: auto;
}

.oxy-modal-backdrop.right .ct-modal {
  margin-left: auto;
}

.oxy-modal-backdrop {
 	overflow: auto;
}

.admin-bar .oxy-modal-backdrop.live {
	padding-top: 32px;
	

@media screen and (max-width: 782px) {
  
	.admin-bar .oxy-modal-backdrop.live {
		padding-top: 46px;
        
	}

}
```

I think if something similar could be added to Oxygen, removing the alignment settings from the modals container and just allowing the modal to be positioned with margins, the overflow problem would be solved. 

demo - http://worried-gazelle.w6.wpsandbox.pro/

**Comment by KittenCodes** [comment] 2019-11-14 21:11
@wplit I've removed the expiry on the demo Sandbox.

**Comment by wplit** [comment] 2020-01-16 21:45
There's a CSS rule I've found that is supposed to be for exactly this - 

overscroll-behavior: contain

https://developers.google.com/web/updates/2017/11/overscroll-behavior/#overlay

**Comment by jvorld** [comment] 2020-07-03 15:06
+1

**Comment by cordschneider** [comment] 2020-09-15 11:40
See the following generic and working fix, taken from https://oxywp.com/en/disabling-page-scrolling-when-opening-the-modal-in-oxygen/ and tested on Oxygen 3.5.

```
/*jQuery Watch Plugin
@author Darcy Clarke
@version 2.0
Copyright (c) 2012 Darcy Clarke
Dual licensed under the MIT and GPL licenses.*/
(function(e){e.fn.watch=function(t,n,r){var i=document.createElement("div");var s=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;var o=window.CustomEvent||function(){return arguments||{}};var u=function(e,t){e="on"+e;var n=e in t;if(!n){t.setAttribute(e,"return;");n=typeof t[e]=="function"}return n};if(typeof n=="function"){r=n;n={}}if(typeof r!="function")r=function(){};n=e.extend({},{throttle:10},n);var a=function(t){var n=this;e.each(this.watching,function(){var e=this;var r=false;var i;for(var s=0;s<e.props.length;s++){i=t[0].attributes[e.props[s]]||t.css(e.props[s]);if(e.vals[s]!=i){e.vals[s]=i;r=true;break}}if(r&&e.callback)e.callback.call(n,new o("AttrChange"))})};return this.each(function(){var o=this;var f=e(this);var l={props:t.split(" "),vals:[],changed:[],callback:r};e.each(l.props,function(e){l.vals[e]=f[0].attributes[l.props[e]]||f.css(l.props[e]);l.changed[e]=false});if(!this.watching)this.watching=[];this.watching.push(l);if(s){var c=new s(function(e){e.forEach(function(e){r.call(o,e)})});c.observe(this,{subtree:false,attributes:true})}else if(u("DOMAttrModified",i)){f.on("DOMAttrModified",r)}else if(u("propertychange",i)){f.on("propertychange",r)}else{setInterval(function(){a.call(o,f)},n.throttle)}})}})(jQuery);

jQuery(document).ready(function($) {

    $('.oxygen-builder-body .oxy-modal-backdrop').css('height','auto');
  
    if($('html').attr('ng-app') == 'CTFrontendBuilder') return;
  
    function scrollbarWidth(){var block = $('<div>').css({'height':'50px','width':'50px'}),indicator = $('<div>').css({'height':'200px'});$('body').append(block.append(indicator));var w1 = $('div',block).innerWidth();block.css('overflow-y','scroll');var w2 = $('div', block).innerWidth();$(block).remove();return (w1 - w2);}
  
    var bg = $('#%%ELEMENT_ID%%').parent('.oxy-modal-backdrop'),
	backsize = $(bg).height();
 
    function fixflex () {
    	var backpos = $(bg).css('align-items'),
	   screenh = $(window).height(),
	   barh = $('#wpadminbar').height();
        $(bg).css({'height':'calc(100% - '+barh+'px)','top':+barh+'px'});
    	if(backsize > screenh) {
           if($(bg).hasClass('right')) {
                $(bg).css('align-items','flex-end');
                $(bg).css('justify-content','flex-start');
           } else if($(bg).hasClass('left')) {
           	$(bg).css('justify-content','flex-start');
           } else {
           	$(bg).css('align-items','flex-start');
           }
    	} else {
            if($(bg).hasClass('right')) {		
                $(bg).css('justify-content','center');
           } else if($(bg).hasClass('left')) {
           	$(bg).css('justify-content','center');
           } else {
           	$(bg).css('align-items',backpos);
           }
        }
    }

    $(window).resize(function(event) {
    	fixflex();
    });
    fixflex();
  
    if(typeof $().watch == 'function') {
	$(bg).watch('display', function() {
            if($(this).css('display')=='flex') {
	        $('body').css({'overflow-y':'hidden', 'height':'100%', 'position':'relative', 'margin-right':scrollbarWidth()+'px'});
                $(this).css('overflow-y','auto');
              	$('.oxy-sticky-header-active').css('padding-right',scrollbarWidth()+'px');
                if($('#%%ELEMENT_ID%%[data-aos*="left"]')) {
                    $(bg).css('overflow-x','hidden');
                }
	     } else if($(this).css('display')=='none') {
                $('.oxy-modal-backdrop').removeClass("live");
		setTimeout(function() {
		    $('body').css({'overflow-y':'auto','margin-right':'0'});
          	    $('.oxy-sticky-header-active').css('padding-right','0');
		}, 300);
	     }
        });
    }
});
```

**Comment by tuqqo** [comment] 2021-02-04 08:45
why is this still not implented in oxygen? i dont see a problem with it as being shipped by default.

**Comment by KittenCodes** [comment] 2021-04-29 14:22
Fixed in v3.8 Beta 1.

**Comment by aalani95** [comment] 2021-08-30 06:30
Any updates on this issue?

**Comment by Sage100** [comment] 2023-07-25 23:26
any updates?

**Comment by CorstoWebDesign** [comment] 2023-11-15 16:58
@KittenCodes and @Spellhammer  Is this on the internal bug fix roadmap at all?

**Comment by Spellhammer** [comment] 2023-11-15 17:01
This was fixed in a previous update.

**Closed by Spellhammer** 2023-11-15 17:01 UTC
Labels: bug, confirmed bug
