### ISSUE TITLE
Enable Query for taxonomies list. 

### ISSUE THREAD

**Issue by tengocode** [soflyy/oxygen-bugs-and-features#2948] opened 2022-06-17 20:20 UTC
Enable taxonomie query, like repeater. Or enable that we can query like in the repeater a list of taxonomie, not custom post type only.

**Comment by janibras** [comment] 2022-06-27 16:00
Same request: https://github.com/soflyy/oxygen-bugs-and-features/issues/2257

**Comment by mrapino** [comment] 2022-06-27 18:56
> Enable taxonomie query, like repeater. Or enable that we can query like in the repeater a list of taxonomie, not custom post type only.

Do you mean building something like the following?

Lots of posts with different terms associated (lets say jobs by location):

LOCATION #1 (term)
 - Job 1 [looped post item 1]
 - Job 2 [looped post item 2]
 - Job 3 [looped post item 3]
LOCATION #2 (term)
 - Job 1 [looped post item 1]
 - Job 2 [looped post item 2]
 - Job 3 [looped post item 3]
LOCATION #3 (term)
 - Job 1 [looped post item 1]
 - Job 2 [looped post item 2]
 - Job 3 [looped post item 3]

If this is not possible in Oxygen, I would like to upvote this, as well (I haven't deeply explored the repeater, so I don't know if this is possible ... please let me know if it is).

**Comment by tengocode** [comment] 2022-06-27 19:03
Hi! Yes I refered somthing like this. 

For Example: 

- Landing Page
- - Category 1 (with featured image)
- - Category 2 (with featured image)
- - Category 3 (with featured image)
- - Category 4 (with featured image)

Right now the repeater can: 

- Post 1
- Post 2
- Post 3
 
And filter with categorys, but we can't show directlye only the categorys, or custom taxonomies.

**Comment by rvducay** [comment] 2023-05-30 04:08
+1

**Comment by Kpudlo** [comment] 2023-05-30 11:06
Closing as duplicate of #2257

**Closed by Kpudlo** 2023-05-30 11:06 UTC
Labels: enhancement
