### ISSUE TITLE
Background Size: "manual" Issue

### ISSUE THREAD

**Issue by tkozohorsky** [soflyy/oxygen-bugs-and-features#3295] opened 2023-05-07 12:50 UTC
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
Issue with property of background-size. When I choose background-size "manual" and enter values width and height, Oxygen Builder automatically add value auto before width and height. This behavior unfortunately denies both values and finally behaves as "auto". Could you please remove value "auto" if I choose manual.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qvrb9y97g6csl.oxygen-demo.qsandbox.org/sample-page/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment] 2023-06-14 14:50
Hello @tkozohorsky, 

Thank you for the report. This error happens when adding a background gradient. As such, I'm marking this as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1004, which discusses this in more detail.

**Closed by Kpudlo** 2023-06-14 14:50 UTC
Labels: bug
