### ISSUE TITLE
Adding Alt Text to the Social Icons - Accessibility Fix

### ISSUE THREAD

**Issue by KnickelsTheEkidna** [soflyy/oxygen-bugs-and-features#2235] opened 2021-06-10 16:43 UTC
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
I would simply want alt text for the SVG's that are used for the Social Icons. Example - Facebook Icon would have alt text of: "Facebook Icon"

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
Accessibility

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
Don't have an example but sites that analyze the site for Acessibility note it as an issue.

**Comment by zuroma999** [comment] 2021-06-12 15:56
Would be great if Oxygen added logical titles to all SVGs (eg "Email" instead of "envelope" for the envelope icon). Would be even better if they didn't add titles at all.

If you're looking for a fix, we add this js code in a code block in our header. It removes all titles from SVGs. Then we just add our own title attribute to any icons we use.

`jQuery(document).ready(function($){ $("svg title").text(""); });`

**Comment by Kpudlo** [comment] 2023-03-01 12:07
Marking this as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2235

**Closed by Kpudlo** 2023-03-01 12:07 UTC
Labels: enhancement
