### ISSUE TITLE
Global Colors - Edit the name of each color

### ISSUE THREAD

**Issue by mbs1337** [soflyy/oxygen-bugs-and-features#1556] opened 2020-09-18 13:53 UTC
**Describe the feature you'd like to see included in Oxygen.**
Edit the name of each global color made in the settings. 

**What are the use cases for this feature?**
If using a Design Set from Oxygen where there is Global Colors added, then it would be a nice feature to just change the color (possible now) and the name (NOT possible now) so it's possible continue to use the design sets, without having to add new colors.

It's not something that is very important, and is considered by me as a "nice to have feature"

**Examples of this feature or functionality.**
Elementor got this function :)

**Comment by d19dotca** [comment] 2022-04-18 07:18
This seems to be a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/84

**Comment by KittenCodes** [comment] 2022-04-18 19:50
Correct, this is a duplicate. Closing.

**Closed by KittenCodes** 2022-04-18 19:50 UTC
Labels: enhancement, Oxygen - Global Settings - Colors
