### ISSUE TITLE
One-click shortcode selection

### ISSUE THREAD

**Issue by pangaeawebservices** [soflyy/oxygen-bugs-and-features#2103] opened 2021-04-17 17:01 UTC
It is super annoying to have to click every box in a long list of shortcodes when needing to resign them. A "select all" option would be really nice.

**Comment by KittenCodes** [comment] 2022-02-22 08:16
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2608. Closing this out.

**Closed by KittenCodes** 2022-02-22 08:16 UTC
Labels: enhancement, Oxygen - Shortcodes
