### ISSUE TITLE
Pagination in second repeater

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2593] opened 2021-12-25 10:38 UTC
Hi:

Please, read before the answer of the first pagination problem fixed here, that I already implemented:
https://github.com/soflyy/oxygen-bugs-and-features/issues/2586#issuecomment-999468945

When I apply  a second repeater in the same homepage, clicking in the pagination of this second repeater, it cause the change of the pagination of all repeaters in the page, not only of the selected repeater.

I expected that only the pagination of the selected repeater would change, or the better if instead of pagination, there was a link "load more" and thus, more posts would be added dynamically without changing the pagination.

https://oxygen-q8nmw838mj2jl.oxygen-demo.qsandbox.me/

User:
admin

Pass:
adminiStrong0

**Comment by KittenCodes** [comment] 2022-01-09 19:00
Thank you for reporting this to us. Replicated and reported internally.

**Comment by Kpudlo** [comment] 2022-11-11 04:02
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1254

**Closed by Kpudlo** 2022-11-11 04:02 UTC
