### ISSUE TITLE
Ability to add icons to menu items

### ISSUE THREAD

**Issue by janknop** [soflyy/oxygen-bugs-and-features#2942] opened 2022-06-16 18:10 UTC
It would be awesome to have ability to add icons to menu items in both cases:  desktop and off-canvas.

Thank you

**Comment by Kpudlo** [comment] 2022-10-23 03:11
Closing this one as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3040 as they are very similar in their requests.

**Closed by Kpudlo** 2022-10-23 03:11 UTC
Labels: enhancement
