### ISSUE TITLE
Add more BREAKPOINTS for resposive design

### ISSUE THREAD

**Issue by LeSill** [soflyy/oxygen-bugs-and-features#3514] opened 2024-03-08 08:59 UTC
Hi everyone,
I'm working on a website, and I've tested the layout on a few different screens: a 25-inch 4K resolution screen, a 19-inch HD resolution screen, a 15-inch laptop screen, a tablet, a mobile device, and so on. However, I've run out of breakpoints to make my design look great on some of the screens.
I looked up how to add more breakpoints on a few websites and saw that someone had requested more a few years ago. However, it doesn't appear that the feature has been implemented as of yet. **A SETTING OF MORE BREAKPOINTS IS ESSENTIAL.** Please implement this function as soon as you can, so we won't have to tell our clients that their website won't look fantastic on all devices.

Many thanks

**Comment by Kpudlo** [comment] 2024-03-08 09:14
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/700

**Closed by Kpudlo** 2024-03-08 09:14 UTC
Labels: enhancement
