### ISSUE TITLE
Global Colors issue in version 3.9

### ISSUE THREAD

**Issue by samjco** [soflyy/oxygen-bugs-and-features#2839] opened 2022-04-22 19:04 UTC
**Describe the bug**
Assigning global color to an element works, however does not show as chosen. See screenshot.

![image](https://user-images.githubusercontent.com/3359062/164778050-9f98eb6d-3f53-406d-b734-cfe518516122.png)

**Comment by wplit** [comment] 2022-04-23 01:23
it's becasuse you're using CSS variables for the colours. Variables have scope, you're probably adding them to the :root () of the webpage, but the builder itself doesn't exist inside of that. So it doesn't know what the variables are.

**Comment by samjco** [comment] 2022-04-23 01:26
I am declaring it in root of my css that I’ve added in the global stylesheets section

**Comment by wplit** [comment] 2022-04-23 01:27
> I am declaring it in root of my css that I’ve added in the global stylesheets section

This is contained within the webpage inside the iframe in the builder, the builder itself is a seperate thing.

**Comment by samjco** [comment] 2022-04-23 01:29
![](https://user-images.githubusercontent.com/3359062/164771947-09cc1152-a3a7-4c38-88de-9c00c6190b5c.png)

**Comment by wplit** [comment] 2022-04-23 01:29
I understand. But the :root() is just referring to the html element inside the iframe. Not the builder, which is a seperate thing outside of that.

**Comment by samjco** [comment] 2022-04-23 01:30
Actually was using automaticcss to first declare colors.

**Comment by wplit** [comment] 2022-04-23 01:38
All of it is only being applied to the site you're building, not the builder. The builder won't pick up any styles from the site, otherwise it could break the UI.

It would be nice if it could pick up the variables, but you'd need to add them to the builder also, seperately. it's not a bug.

I'll add an image to show what i mean, the lower square is the html tag where all your variables are being added, inside the iframe, everything outside is the builder, so is unaware of the variables or any CSS inside there.

<img width="1920" alt="Screen Shot 2022-04-23 at 11 34 55 am" src="https://user-images.githubusercontent.com/43051571/164861479-83009bde-8c35-4fed-bba7-718770c5f427.png">

**Comment by samjco** [comment] 2022-04-23 01:47
So the vars needs to be declared before oxygen. Perhaps enqueued using Snippets?

**Comment by wplit** [comment] 2022-04-23 01:51
> So the vars needs to be declared before oxygen. Perhaps enqueued using Snippets?

I haven't tested specifically for the variables/color picker. but the hook 'oxygen_enqueue_ui_scripts' is how you can add CSS to the builder UI.

See the second example code - https://wpdevdesign.com/oxygen-developers-guide/

**Comment by KittenCodes** [comment] 2022-04-23 09:30
Closing as this isn't a bug.

**Closed by KittenCodes** 2022-04-23 09:30 UTC
Labels: bug
