### ISSUE TITLE
A gap value with any non PX unit on a class applied to a section outputs double units on the front-end

### ISSUE THREAD

**Issue by SeboF** [soflyy/oxygen-bugs-and-features#3033] opened 2022-08-05 06:58 UTC
**Describe the bug**
Filling out the gap property works in the backend. In the frontend the unit is doubled and causing an error, eg. "10remrem"
In the sandbox a class with the gap property is added to the section.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qq3dh6m63bcnl.oxygen-demo.qsandbox.me/hello-world/

**Comment by Spellhammer** [comment] 2022-08-05 13:02
Thanks for the report.

Confirmed and reported internally.

As an immediate workaround, you can use the "none" unit and type <value>rem manually and it will output correctly.

**Comment by sunnyt7** [comment] 2023-01-12 23:42
This is still a bug, and the workaround no longer works because it auto selects the rem unit. Only workaround now is custom CSS 😞

**Comment by Spellhammer** [comment] 2023-03-16 15:17
This should be fixed in the forthcoming 4.6 Beta 1.

**Closed by Spellhammer** 2023-03-16 15:17 UTC
Labels: bug, confirmed bug, slated for release
