### ISSUE TITLE
Code Block Doesn't Execute Javascript or CSS in Reusable Part

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#3235] opened 2023-02-13 22:17 UTC
Oxygen 4.4

This occurs for some code blocks, but not others. Adding a shortcode to the part may be what causes the issue.

**Describe the bug**
Using a code block within a reusable part fails to include the JavaScript or CSS in a reusable part with certain elements.

**Reproduction**
1. Create reusable part.
   1. Add code block javascript such as `console.log("bla")`.
2. Create template.
   1. Add single reusable part to template.
3. Create page using template.
4. Check page (message isn't shown in console, but PHP works).

Console message should be shown.

**Comment by switchupcb** [comment] 2023-02-13 22:17
The workaround makes me very sad too.

![image](https://user-images.githubusercontent.com/81384235/218587153-5dfb1546-e6c1-4001-8793-c8b16e76be3b.png)

**Comment by Kpudlo** [comment] 2023-03-04 19:41
Duplicate of #319

**Closed by Kpudlo** 2023-03-04 19:41 UTC
Labels: bug

**Comment by switchupcb** [comment] 2023-03-06 17:25
This issue was not constrained to the editor. @Kpudlo

**Comment by Kpudlo** [comment] 2023-03-06 18:21
@switchupcb, I could not reproduce this on a sandbox site where the JavaScript didn't work on the front end. If you still have this issue, please see if you can recreate it on a Sandbox site (https://oxygenbuilder.com/try/) and send a link to the Sandbox, or send us a Support Ticket (https://oxygenbuilder.com/support) with login credentials to a site where this issue occurs. We'll be glad to investigate further.
