### ISSUE TITLE
Oxygen 4.0 RC1 - Bug in border settings - super slow 

### ISSUE THREAD

**Issue by Schokolader** [soflyy/oxygen-bugs-and-features#2864] opened 2022-05-09 17:20 UTC
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
If you go to Border settings and select solid and try to enter a value in the color field it is super slow. There seems 
to be a bug. https://share.getcloudapp.com/6quZyRKn

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

1. Add an Image 
2. Go to Border Settings
3. Click on Solid and try to add a color via variables
4. It immediately starts to get super slow and buggy. 

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by wplit** [comment] 2022-05-10 03:01
same as https://github.com/soflyy/oxygen-bugs-and-features/issues/2836

**Comment by KittenCodes** [comment] 2022-05-10 06:16
Closing as duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2836.

**Closed by KittenCodes** 2022-05-10 06:16 UTC
Labels: bug
