### ISSUE TITLE
[3.8 ALPHA] ORDER_BY MULTIPLE

### ISSUE THREAD

**Issue by RaulGandia** [soflyy/oxygen-bugs-and-features#2108] opened 2021-04-18 11:33 UTC
**Describe the bug**
Problems and improvements with Order_by and Order in Advanced Query.

Many times you need to sort by more than one field at a time. For example, the list is ordered 1st by price and for those of the same price that are ordered by Name.
In advanced query it is impossible to achieve this.
if you put 2 order_by, just take the last one you put.
As a substantial improvement, it should be allowed in the order_by of advanced query. 1 .- Add different fields in same order_by statement and for each of these fields, be able to specify the Order (ASC or DESC) 

example of args pased to a personal query. with an order by multiple.
$args = [
              "post_type" => [
                "vino"
              ],
              "post_status" => [
                "publish"
              ],
              "meta_query" => [
                "0" => [
                  "key" => "publicado",
                  "compare" => "=",
                  "type" => "DECIMAL(16,4)",
                  "value" => "1"
                ],
                "1" => [
                  "key" => "unidades_disponibles",
                  "compare" => ">",
                  "type" => "DECIMAL(16,4)",
                  "value" => "0"
                ],
                "sort_0" => [
                  "key" => "precio_restaurante",
                  "type" => "DECIMAL(16,4)"
                ]
              ],
              **"orderby" => [
                "sort_0" => "ASC",
                "title" => "ASC"
              ],**
              "posts_per_page" => "10"
            ];

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Desktop (please complete the following information):**
 - Browser [firefox]
 - Oxygen Version [e.g. 3.8 Alpha]

**Comment by RaulGandia** [comment] 2021-04-18 18:11
Like other issue [3.8 Alpha] Multiples Meta_query's don't work, you can change this issue like enhancement..

**Comment by Kpudlo** [comment] 2023-06-15 16:03
Closing as duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2331

**Closed by Kpudlo** 2023-06-15 16:03 UTC
Labels: enhancement
