### ISSUE TITLE
No social icons displayed

### ISSUE THREAD

**Issue by dstorozilovs** [soflyy/oxygen-bugs-and-features#3083] opened 2022-09-20 06:22 UTC
**In oxygen editor all blocks with social icons are displayed with bug. Also if div block height is set to less than 80px in preview mode it still shows as a square with 80px height which broke the design process.**

A link to a Sandbox site where the bug has been reproduced: https://oxygen-qlp6g92hfj2nl.oxygen-demo.qsandbox.me/sample-page/
The link to a Sandbox install where the issue is present: https://oxygen-qlp6g92hfj2nl.oxygen-demo.qsandbox.me/wp-admin/edit.php?post_type=page

![bug](https://user-images.githubusercontent.com/100198597/191179680-7a325382-43c9-475f-a522-fe8a816e0a62.png)
![image](https://user-images.githubusercontent.com/100198597/191180531-50ccf04b-04ff-4df1-ae26-6fed141a084b.png)

**Comment by Spellhammer** [comment] 2022-09-20 11:07
Unable to see the issue on the provided sandbox. Can you let me know which browser and OS you're using so I can do some more accurate testing?

> Also if div block height is set to less than 80px in preview mode it still shows as a square with 80px height which broke the design process.

This is not a bug. Containers are restricted from becoming smaller than 80x80 in the builder so that you can still drag items into them. You can override this via custom CSS and min-height/min-width.

**Comment by dstorozilovs** [comment] 2022-09-21 06:58
Hi, I am using Firefox. 

**Steps to reproduce the behavior:**
1. Go to 'Oxygen builder'
2. Click on 'Add element' -> 'Library' -> 'Design sets' -> 'Wedding' (actually all sets have the same issue) -> 'Sections & Elements' -> 'Footers' 
3. Choose 'Footer Centered'
4. See the bug (no social icons displayed).

**Comment by Kpudlo** [comment] 2022-10-23 03:15
Confirmed and reported internally.

**Comment by Spellhammer** [comment] 2022-11-18 15:36
Fixed in 4.2 beta 1.

**Closed by Spellhammer** 2022-11-18 15:36 UTC
Labels: bug, confirmed bug
