### ISSUE TITLE
Icon Pseudo Class :hover Broken. Does not Render on Front-End, only inside Builder

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#3203] opened 2023-01-23 06:50 UTC
<img width="89" alt="Screenshot 2023-01-23 at 1 29 30 AM" src="https://user-images.githubusercontent.com/12590359/213980588-3f1b6a4d-25be-4d3d-964e-901920e9a22c.png">

Oxygen's Icon widget is broken. Hover pseudo class does not work. Replicated on Oxygen's SandBox: [https://oxygen-q8a8p9zlmzm8.oxygen-demo.qsandbox.org/](https://l.facebook.com/l.php?u=https%3A%2F%2Foxygen-q8a8p9zlmzm8.oxygen-demo.qsandbox.org%2F%3Ffbclid%3DIwAR26-ADnuG0iKXgAzBIJ-Rs1a3hJHOYviuMah7mG9P-4UiOvvH8DGN36uiA&h=AT2QbFeoN-djWTFViUYutHiqLRrIk9KJOkJTPXVoyDZHWDIUjrYqOUy_lz5h_I7ifUR6b2n-5YuQqX0xRUR63ZdNCO3C3QgUYImJOTEkj10nESSqXVZMvwhY7U_yqER2EZQ14U5K2Ts25suANPd6mhM&__tn__=-UK-R&c[0]=AT2TqGZEdTg4AuUSmt_P6LIymFtZk-0-U_oZMauesPxGfmkQL9Ue4Q9bYDSfK7yhI8If12rZ_OhsrIsYz4gFD6vqCNBRRhLxOEfrhhCcMP8682dmfc9Rr899kBwojz1WfBr-6c8f_LtTBqzpT9595hmQMIDfLukunqPYFoI)
Access Code: 3518

Steps to recreate issue: 
1. Add Icon widget
2. Select Icon Style Solid
3. Set Color and Background Color 
4. Select state and choose :hover
5. Set the hover values for Color and Background Color.
6. View on Front-End

Note that inside the Builder, the hover effect works perfectly.

<img width="731" alt="Icon-hover-added-in-Oxy" src="https://user-images.githubusercontent.com/12590359/213983178-cd34f44a-940d-4270-840b-da39906e4624.png">

<img width="1024" alt="Hover-Empty-FireFox-Inspector-Oxygen" src="https://user-images.githubusercontent.com/12590359/213983516-35980e71-595e-4a09-93a1-2dbf6f1e3f74.png">

**Comment by Kpudlo** [comment] 2023-02-09 12:34
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/842 and slated for release

**Closed by Kpudlo** 2023-02-09 12:34 UTC
Labels: bug
