### ISSUE TITLE
Gallery Layout "Images per row" to obey viewport controls

### ISSUE THREAD

**Issue by dubpir8** [soflyy/oxygen-bugs-and-features#3365] opened 2023-07-26 07:26 UTC
**Describe the feature you'd like to see included in Oxygen.**

In the Layout settings of the native Oxygen Gallery element, changes to the "Images per row" setting should obey the viewport settings. Here is a screen-shot of the field: https://ibb.co/wM9kBxw
For example, in the full width screen we can set it to 8 images per row and screen-widths lower than 768 we can set it to 4 images per row. Currently the setting sticks for all viewports, no matter which viewport you change the setting at.

**What are the use cases for this feature?**
So that gallery images can be viewed more easily on narrow screens. As you can see in the following screen-shot, 8 images per row means you can't view the details of the award badges, where on full-screen it is fine at 8 images per row: https://ibb.co/wM9kBxw

**Comment by Kpudlo** [comment] 2023-09-29 17:16
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3001

**Closed by Kpudlo** 2023-09-29 17:16 UTC
Labels: enhancement
