### ISSUE TITLE
Ability to change image when image is setup as Media Library (using ID instead of URL) for block library

### ISSUE THREAD

**Issue by webecks** [soflyy/oxygen-bugs-and-features#2578] opened 2021-12-15 04:45 UTC
**Describe the feature you'd like to see included in Oxygen.**
- Image that is setup using Media Library (using ID) like this https://d.pr/i/NzYgFl is good, because it's using WordPress srcset which is good for getting high score on google page speed and it's just the correct way of displaying images nowadays
- However, when we use this as block library, we cannot change the image.
- It is possible to change the image when the image is setup as Image URL like this https://d.pr/i/qcj84Y but that is not srcset
- Please look into this video https://share.getcloudapp.com/eDulW8oJ

**What are the use cases for this feature?**
- Use it as block library in Gutenberg editor

**Examples of this feature or functionality.**
- Nowadays, the correct way of displaying images would be using srcset.
- Please enable functionality to replace the image when it is used as block library

Let me know if you need further information.

**Comment by webecks** [comment] 2021-12-15 04:46
This could be a bug or a new feature. Please implement this into the next Oxygen release. Hopefully this would be straight-forward and fast to implement, as this is an important feature to display the image correctly in the front-end.

**Comment by KittenCodes** [comment] 2021-12-16 12:32
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1223

**Closed by KittenCodes** 2021-12-16 12:32 UTC
Labels: enhancement
