### ISSUE TITLE
Align Self in Flexbox Child controls doesn't work

### ISSUE THREAD

**Issue by luisceladita** [soflyy/oxygen-bugs-and-features#2116] opened 2021-04-21 13:24 UTC
**Describe the bug**
The Align Self setting specifies the alignment for the selected item inside the flex container. There are five options available: auto, left, center, right, stretch
but the editor use that values "left" and "right" which are incorrect in Chrome, Firefox, Opera, etc".
This should be "flex-start" or "flex-end"

**A link to a demo site where the bug has been reproduced**
https://oxygen-q8aa778x2pgfl.oxygen-demo.qsandbox.me/flex-bug/

**Steps required to reproduce the bug:**
1. Create a section
2. Put a text widget inside
3. Set align-self of the text to "left" or "right".

**Comment by Spellhammer** [comment] 2021-04-21 14:03
Thanks for your report.

This is a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/259 and has already been reported internally.

**Closed by Spellhammer** 2021-04-21 14:03 UTC
Labels: bug
