### ISSUE TITLE
OXYGEN 4 ALPHA

### ISSUE THREAD

**Issue by RaulGandia** [soflyy/oxygen-bugs-and-features#2626] opened 2021-12-28 22:47 UTC
Frontend gives a wordpress crash error, with 👍 
Translatepress and/or wpgridbuilder oxygen complement

**Comment by KittenCodes** [comment] 2022-01-09 09:58
Closing, due to lack of information and reproduction steps.

**Closed by KittenCodes** 2022-01-09 09:58 UTC
Labels: bug

**Comment by barrychapman** [comment] 2022-06-02 04:59
this is still an issue
