### ISSUE TITLE
do_shortcode_tag filter broken in 4.0 Alpha 2

### ISSUE THREAD

**Issue by swinggraphics** [soflyy/oxygen-bugs-and-features#2729] opened 2022-02-02 22:33 UTC
I see there is already a TODO marked in templates.php for this. I'm logging it here because I won't be able to upgrade any of the sites I use Oxygen on until this is completed. Please let me know if it would be more appropriate to raise the issue another way. Thanks

**Comment by GC-DK** [comment] 2022-02-03 08:48
This is also a major issue for us. It's probably the biggest concern right now on our alpha 2 testing site.

**Comment by KittenCodes** [comment] 2022-02-03 16:17
@swinggraphics @GC-DK 

Please can we have an example of how you're using the do_shortcode_tag filter so that we can check this out?

Thanks!

**Comment by swinggraphics** [comment] 2022-02-03 18:49
@KittenCodes These are the ways I'm using it in a standard plugin I install alongside Oxygen:
```
/* Wrap logo in h1 tag on home page */
function hcps_logo_h1( $output, $tag, $attr ) {
	if ( defined( 'SHOW_CT_BUILDER' ) ) return $output;
	if ( ! is_front_page() || 'ct_image' != $tag ) return $output;
	$options = json_decode( $attr['ct_options'] );
	if ( 'site-logo' != $options->selector ) return $output;
	return "<h1>$output</h1>";
}
add_filter( 'do_shortcode_tag', 'hcps_logo_h1', 10, 3 );


/* Fix Oxygen Pro Menu */
function hcps_oxygen_pro_menu_filter( $output, $tag, $attr ) {
	if ( defined( 'SHOW_CT_BUILDER' ) ) return $output;
	if ( 'oxy-pro-menu' != $tag ) return $output;
	// Change element to nav tag
	$output = preg_replace( '#^(\s*)<div(.*)</div>(?=.*<script)(.+)$#s', '$1<nav$2</nav>$3', $output );
	// Make open icon keyboard accessible
	$output = preg_replace( '#(class="[^"]*oxy-pro-menu-mobile-open-icon)#', 'role="button" tabindex="0" onkeydown="if(13===event.which||32===event.which){this.click();return false;}" $1', $output );
	// Make close icon keyboard accessible
	$output = preg_replace( '#(class="[^"]*oxy-pro-menu-mobile-close-icon)#', 'role="button" tabindex="0" onkeydown="if(13===event.which||32===event.which){this.click();return false;}" $1', $output );
	return $output;
}
add_filter( 'do_shortcode_tag', 'hcps_oxygen_pro_menu_filter', 10, 3 );


/* Make Oxygen Testimonial mirror Gutenberg */
function hcps_oxygen_testimonial_filter( $output, $tag, $attr ) {
	if ( defined( 'SHOW_CT_BUILDER' ) ) return $output;
	if ( 'oxy_testimonial' != $tag ) return $output;
	// Change element to blockquote tag
	$output = preg_replace( '#^(\s*)<div(.*)</div>(\s*)$#s', '$1<blockquote$2</blockquote>$3', $output );
	// Change author wrap to cite tag
	$output = preg_replace( '#<div(\s+class=[\'"]oxy-testimonial-author-wrap[\'"]>.+)</div>\s*(</div>\s*</blockquote>)#s', '<cite$1</cite>$2', $output );
	// Wish there were option to remove placeholder image
	// @see https://github.com/soflyy/oxygen-bugs-and-features/issues/1663
	if ( strpos( $attr['ct_options'], 'no-photo' ) ) {
		$output = preg_replace( '#<div\s+class=[\'"]oxy-testimonial-photo-wrap.+?</div>#s', '', $output );
	}
	return $output;
}
add_filter( 'do_shortcode_tag', 'hcps_oxygen_testimonial_filter', 10, 3 );

```

**Comment by GC-DK** [comment] 2022-02-04 07:53
In our case it's used with WP Grid Builder Oxygen add-on. It's missing the attribute in apply_filters. I think it's already addressed here: https://github.com/soflyy/oxygen-bugs-and-features/issues/2595

**Comment by swinggraphics** [comment] 2022-02-04 15:59
`pre_do_shortcode_tag` filter no longer works, too. For example, my workaround for the BUG (not enhancement, as invalid code—block elements inside inline elements—is a bug) #1381 doesn't work:
```
/* Remove span wrapper from Oxygen Content element */
function hcps_remove_oxygen_content_wrapper( $return, $tag, $attr, $m ) {
	if ( defined( 'SHOW_CT_BUILDER' ) ) return $return;
	if ( 'ct_span' != $tag ) return $return;
	die('here');
	if ( ! preg_match( '#^\[oxygen [^\]]+ data=[\'"]content[\'"]#', $m[5] ) ) return $return;
	return do_shortcode( $m[5] );
}
add_filter( 'pre_do_shortcode_tag', 'hcps_remove_oxygen_content_wrapper', 10, 4 );
```

**Comment by swinggraphics** [comment] 2022-02-04 16:40
Related #2732

**Comment by sc0ttkclark** [comment] 2022-02-07 05:09
Proposing this to be closed as a duplicate of #2595

**Comment by KittenCodes** [comment] 2022-02-07 07:36
Thanks @swinggraphics @GC-DK

**Closed** 2022-02-07 07:35 UTC
Labels: bug

**Comment by KittenCodes** [comment] 2022-02-10 09:06
This should be fixed in v4 Beta 1.

**Comment by GC-DK** [comment] 2022-02-10 10:58
Any chance you can tell when beta 1 is ready for download?
