### ISSUE TITLE
Add one or more additional Width Breakpoints 

### ISSUE THREAD

**Issue by nikonik11** [soflyy/oxygen-bugs-and-features#3022] opened 2022-07-26 13:52 UTC
Hello 

I use Oxygen Builder every day to build all my websites in my agency 

There is a feature that I really miss, it's the ability to add a fifth width breakpoint 

One more width breakpoint would allow me to adjust my responsiveness much more easily. Today, even if most people use 24" screens, many others are starting to use 27", 32", 34" etc...

Therefore, 4 width breakpoints are not enough to correctly adjust my responsivity from the smallest smartphone to large 32" screens.

Thank you for considering my request

Sincerely

**Comment by Kpudlo** [comment] 2022-07-27 16:11
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/700

**Closed by Kpudlo** 2022-07-27 16:11 UTC
Labels: enhancement
