### ISSUE TITLE
Please clean up PHP Notices

### ISSUE THREAD

**Issue by cvladan** [soflyy/oxygen-bugs-and-features#883] opened 2020-03-05 17:03 UTC
**Describe the bug**
There is a lot of PHP Notices in `debug_log`. Please, make them go away - it should be quite simple. I see you emphasize on "precision" and code lightness, so I expected 0-warnings ;) 

**To Reproduce**
Do anything

**Expected behavior**
Not to have PHP Warnings or Notices

**What actually happens**

```
PHP Notice:  Undefined index: icon-layout in /oxygen/component-framework/components/classes/social-icons.class.php on line 190
PHP Notice:  Undefined index: icon-space-between-icons in /oxygen/component-framework/components/classes/social-icons.class.php on line 191
PHP Notice:  Undefined index: icon-space-between-icons in /oxygen/component-framework/components/classes/social-icons.class.php on line 192
PHP Notice:  Undefined index: icon-space-between-icons in /oxygen/component-framework/components/classes/social-icons.class.php on line 197
PHP Notice:  Undefined index: icon-space-between-icons in /oxygen/component-framework/components/classes/social-icons.class.php on line 198
PHP Notice:  Undefined index: icon-style in /oxygen/component-framework/components/classes/social-icons.class.php on line 199
PHP Notice:  Undefined index: icon-style in /oxygen/component-framework/components/classes/social-icons.class.php on line 201
PHP Notice:  Undefined index: icon-style in /oxygen/component-framework/components/classes/social-icons.class.php on line 204
PHP Notice:  Undefined index: icon-style in /oxygen/component-framework/components/classes/social-icons.class.php on line 206
PHP Notice:  Undefined index: icon-background-color in /oxygen/component-framework/components/classes/social-icons.class.php on line 207
PHP Notice:  Undefined index: icon-style in /oxygen/component-framework/components/classes/social-icons.class.php on line 211
PHP Notice:  Undefined index: icon-background-hover-color in /oxygen/component-framework/components/classes/social-icons.class.php on line 213
PHP Notice:  Undefined index: icon-use-brand-colors in /oxygen/component-framework/components/classes/social-icons.class.php on line 219
PHP Notice:  Undefined index: icon-style in /oxygen/component-framework/components/classes/social-icons.class.php on line 246
PHP Notice:  Undefined index: arguments in /oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php on line 140
PHP Notice:  Undefined index: arguments in /oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php on line 140
```

**Comment by alriksson** [comment] 2020-03-12 07:13
This was reported months ago over a support ticket. Together with Oxygens ACF integration to be slow when using the builder.



Notice | Trying to get property 'post_type' of non-object | 4 | +wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php:55 | Plugin: oxygen
-- | -- | -- | -- | --
Notice | Trying to get property 'ID' of non-object | 4 | +wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php:56 | Plugin: oxygen
Notice | Trying to get property 'ID' of non-object | 4 | +wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php:83 | Plugin: oxygen
Notice | Undefined index: button-text-color | 3 | +wp-content/plugins/oxygen/component-framework/components/component.class.php:3030 | Plugin: oxygen
Notice | Undefined index: button-size | 3 | +wp-content/plugins/oxygen/component-framework/components/component.class.php:3031 | Plugin: oxygen
Notice | Undefined index: button-color | 9 | +wp-content/plugins/oxygen/component-framework/components/component.class.php:3035 | Plugin: oxygen
Notice | Undefined index: button-text-color | 9 | +wp-content/plugins/oxygen/component-framework/components/component.class.php:3036 | Plugin: oxygen
Notice | Undefined index: button-size | 9 | +wp-content/plugins/oxygen/component-framework/components/component.class.php:3037 | Plugin: oxygen

**Comment by shoelaced** [comment] 2020-03-31 13:15
The Query Monitor plugin freaks out over Oxygen's PHP errors as well.

**Comment by benfavre** [comment] 2020-04-18 08:40
Some feedback from oxygen team in this repo would be a good Idea.
The whole repo just looks ridiculous. Full of people reporting bugs and 0 feedback.

**Comment by alexanderkladov** [comment] 2020-04-23 08:32
Please for the love god fix these errors! My log file on a local dev server bloats up to about 4Gb by the end of every workday. This is ridiculous.

**Comment by alexanderkladov** [comment] 2020-04-25 19:24
Doesn't seem like anyone is gonna fix this any time soon, so I took matters into my own hands.

I specifically had a massive problem with Oxygen WooCommerce extension throwing millions of errors due to missing `button_priority` index. Error looks like this:
```
PHP Notice:  Undefined index: button_priority in /Applications/MAMP/htdocs/dev/www.demo.test/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 44
```

To fix it, simply check if `button_priority` property actually exists on line 37 in `/oxygen/component-framework/api/oxygen.element.class.php`

Change it from this:
```php
$this->params['button_priority']= $other_options['button_priority'];
```

To this:
```php
$this->params['button_priority']= isset( $other_options['button_priority'] ) ? $other_options['button_priority'] : 10;
```

Now my log is finally quiet, as it should be.

**Comment by alexanderkladov** [comment] 2020-04-25 19:44
Another few noisy ones worth fixing are in
1. `/oxygen/component-framework/api/oxygen.element.class.php`. 

    Change **line 282** from this:
    ```php
    $html = $this->params['html_template'];
    ```
    To this:
    ```php
    $html = isset( $this->params['html_template'] ) ? $this->params['html_template'] : '';
    ```
    
    Change **line 303** from this:
    ```php
    if ($this->params['inlineJS']!==""){
    ```
    To this:
    ```php
    if (isset( $this->params['inlineJS'] ) && $this->params['inlineJS']!==""){
    ```


1. `/oxygen/component-framework/components/classes/dynamic-list.class.php`

    Change **line 1379** from this:
    ```php
    if ($arr['name'] === 'oxy_dynamic_list' && $key == 'children') {
    ```
    to this:
    ```php
    if (isset($arr['name']) && $arr['name'] === 'oxy_dynamic_list' && $key == 'children') {
    ```

That eliminated 99% of errors for me. I can put up with the rest.

**Comment by michfield** [comment] 2020-05-11 20:17
C'mon guys! This is getting really annoying. Still not fixed in 3.3?
Is it so hard? ... just to apply suggestions specified here

I don't believe anymore that this project has any future...

**Comment by alexanderkladov** [comment] 2020-05-11 20:45
@michfield I'd say they are ahead of the game, when it comes to WP site builders, but they are definitely lacking, when it comes to responsiveness regarding Oxygen community feedback/requests, that's for sure. Which is a shame. They have the potential to take over professional WP developer market, if only they were a bit faster to implement/fix a few long-overdue features/bugs. Right now a lot of the professional WP devs are probably still worried about the future of Oxygen, which keeps them from fully embracing it. Some clear communication & faster release cycle could've helped clear this out.

Having said that, Oxygen is already so good, that I am willing to close my eyes on a lot of these issues. But if it will continue for much longer, we might be better off to just go with plain WP + ACF Pro, which can pretty much allow you to build everything in an even more efficient way, but with a bit more dev work.

**Comment by cvladan** [comment] 2020-05-12 23:58
I won't patch plugin every time I update it! And I really need a solution until there is a proper upstream fix. So I simply disable any PHP notice coming from any Oxygen file. Just put these lines wherever you want, and it should do the trick...

```
/* disable oxygen related notices only */
set_error_handler(function($errno, $errstr, $errfile) {
  return (strpos($errfile, 'plugins/oxygen') !== false);
}, E_NOTICE);
```

**Comment by alexanderkladov** [comment] 2020-05-15 09:55
@cvladan I've never seen this approach before, sound like a perfect temporary solution for this error madness! Thanks!

Till now I simply patched everything up myself in Oxygen and ignored all of their newer releases, cos I knew they haven't fixed any of these bugs.. "good thing" they haven't released anything worth updating for recently, so having an outdated version of Oxygen didn't bother me too much.

**Comment by robrecord** [comment] 2020-06-02 10:02
This will also suppress deprecation notices:
```
/* disable oxygen related notices only */
set_error_handler(function ($errno, $errstr, $errfile) {
  return (strpos($errfile, 'plugins/oxygen') !== false);
}, E_NOTICE | E_DEPRECATED);
```

**Comment by ddon** [comment] 2020-06-17 17:24
Checked 3.4 Beta 1, still filling up error log with errors and warnings... great to see some solutions here :)

**Comment by shoelaced** [comment] 2020-07-03 17:36
3.4 is the best update yet, loving it, great job team... but it's truly unbelievable that these errors/notices aren't fixed yet.

**Comment by alexanderkladov** [comment] 2020-07-03 18:00
@shoelaced Agree 100%.

I still can't even update to 3.4, because I had to patch up all of these stupid errors myself, and to me that's way more important than undo/redo (even though it is amazing). Why it's more important? Cos the god damn site wouldn't load because of the millions of errors that Oxygen would throw otherwise! So what's good is there in having undo/redo, when my entire workflow comes to a standstill due to error-related loading issues?! This is ridiculous..

**Comment by ddon** [comment] 2020-07-03 18:02
this helped a lot! :)

@robrecord thanks! :)

/* disable oxygen related notices only */
set_error_handler(function ($errno, $errstr, $errfile) {
  return (strpos($errfile, 'plugins/oxygen') !== false);
}, E_NOTICE | E_DEPRECATED);

**Comment by shoelaced** [comment] 2020-07-03 18:15
@ddon Did you put that in your config or a plugin?

**Comment by alexanderkladov** [comment] 2020-07-03 18:51
@shoelaced with Oxygen, due to the lack of themes (i.e. `functions.php`), the easiest thing to do is to use this awesome [Code Snippets plugin](https://en-ca.wordpress.org/plugins/code-snippets/).

**Comment by ddon** [comment] 2020-07-03 19:56
I put in my own plugin, but sure, Code Snippets is a great idea for sure!

**Comment by vaztimur** [comment] 2020-07-07 11:41
> 3.4 is the best update yet, loving it, great job team... but it's truly unbelievable that these errors/notices aren't fixed yet.

I guess, they are waiting for a third-party plugin like OxyBugs for fixing it, to let their friends earn some money selling plugins with features, which should be included in the core plugin

**Comment by ddon** [comment] 2020-07-07 17:19
Let's build one! :) OxyBugs, I like it!

**Comment by twistedpixel** [comment] 2020-08-13 10:49
The problem is that it's lazy coding (not checking existence of index before attempted use) and unfortunately not just with Oxygen. WP core code has this issue too with many of the widgets in 'wp-includes/widgets'.

Maybe a last minute addition to PHP 8 will be the removal of notices altogether because there are too many lazy PHP devs 🙃

**Comment by artbrander** [comment] 2020-08-13 11:06
Has anyone tried the 3.5 beta? Are the notices still in there? There's no mention of it in the changelog.

**Comment by twistedpixel** [comment] 2020-08-13 11:14
> Has anyone tried the 3.5 beta? Are the notices still in there? There's no mention of it in the changelog.

Still not fixed in 3.5 beta 1.

**Comment by KittenCodes** [comment] 2020-10-17 10:54
Icon error messages fixed in v3.6 Beta: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/

**Closed by KittenCodes** 2020-10-17 10:54 UTC
Labels: bug, confirmed bug

**Comment by yildirimsertbas** [comment] 2021-03-26 10:35
> this helped a lot! :)
> 
> @robrecord thanks! :)
> 
> /* disable oxygen related notices only */
> set_error_handler(function ($errno, $errstr, $errfile) {
> return (strpos($errfile, 'plugins/oxygen') !== false);
> }, E_NOTICE | E_DEPRECATED);

where did you add it?

**Comment by robrecord** [comment] 2021-03-26 10:57
> > this helped a lot! :)
> > @robrecord thanks! :)
> > /* disable oxygen related notices only */
> > set_error_handler(function ($errno, $errstr, $errfile) {
> > return (strpos($errfile, 'plugins/oxygen') !== false);
> > }, E_NOTICE | E_DEPRECATED);
> 
> where did you add it?

I think I created a mu-plugin file but you could try adding it to wp-config.php or functions.php, not sure if either would work as well though

**Comment by ddon** [comment] 2021-03-26 14:41
I opened oxygen plugin and pasted code in there

**Comment by YvKarman** [comment] 2023-06-27 10:16
This is still going on, or has made a comeback.

`"PHP message: PHP Warning: Undefined array key "icon-color" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3034PHP message: PHP Warning: Undefined array key "icon-padding" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3036PHP message: PHP Warning: Undefined array key "icon-size" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3037 PHP message: PHP Warning: Undefined array key "icon-color" in public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3034PHP message: PHP Warning: Undefined array key "icon-padding" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3036 PHP message: PHP Warning: Undefined array key "icon-size" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3037PHP message: PHP Warning: Undefined array key "icon-background-color" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3035PHP message: PHP Warning: Undefined array key "icon-padding" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3036 PHP message: PHP Warning: Undefined array key "icon-size" in /public/wp-content/plugins/oxygen/component-framework/component-init.php on line 3037" while reading response header from upstream, client: , server:, request: "POST /?p=292741&action=ct_save_components_tree&ct_inner=true&nonce=6b7f1f22e2&post_id=292741 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-onlinehoortoestels.sock:", host: "", referrer: "?p=292741&ct_build`

and:
`
"PHP message: PHP Warning: Attempt to read property "ID" on bool in /public/wp-content/plugins/oxygen/component-framework/admin/cpt-templates.php on line 477" while reading response header from upstream, client: , server: , request: "GET /wp-admin/post-new.php?post_type=shop_order HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-, host: "807", referrer: "/wp-admin/post-new.php?post_type=shop_order"`

finally:

`"PHP message: PHP Warning: Undefined property: stdClass::$ID in /public/wp-content/plugins/oxygen/component-framework/components/classes/dynamic-list.class.php on line 398" while reading response header from upstream, client: , server: , request: "POST /?wpgb-ajax=refresh&lang=de&_pagination=3 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-.sock:", host: "", referrer: "/parent-category/sub-category/?_pagination=3"`
