### ISSUE TITLE
Custom css loading feature on Oxygen Stylesheet Editor.

### ISSUE THREAD

**Issue by MaximeStarssed** [soflyy/oxygen-bugs-and-features#3208] opened 2023-01-25 09:31 UTC
**Describe the feature you would like to see included in Oxygen.

I would like to be able to customize on which pages my CSS files made with Oxygen Stylesheet Editor are displayed.
In the same way that it is possible to set conditions for templates, I would like to be able to add conditions where the CSS files load.

**What are the use cases for this feature?
For example, if a stylesheet only for Woocommerce, it would only load on the shopping pages.

**Comment by Kpudlo** [comment] 2023-01-25 21:30
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/18

**Closed by Kpudlo** 2023-01-25 21:30 UTC
Labels: enhancement
