### ISSUE TITLE
"Robust" Mega Menus 

### ISSUE THREAD

**Issue by jmcbade** [soflyy/oxygen-bugs-and-features#587] opened 2019-09-29 09:28 UTC
This one is easy to demonstrate.  Just look at how Max Mega Menus works.  If we add this as a plugin there are issues - one being more overhead which effect performance. Of course possible conflicts with Oxygen's plugins are also possible. I believe and "integrated" solution would work well in circumventing some of the overhead - yes?

[https://www.megamenu.com/](url)

**Comment by louisreingold** [comment] 2019-09-29 21:03
> If we add this as a plugin there are issues - one being more overhead which effect performance. Of course possible conflicts with Oxygen's plugins are also possible

Neither of those statements are true.

**Comment by jmcbade** [comment] 2019-09-29 23:10
Not trying to be argumentative, but in my testing with and without the megamenu plugin, I see a performance difference. Would you be open to the discussion (as it is also being discussed on FBook), that a megamenu type functionality native in Oxygen would be desirable and useful?  Is there a way to do this now?  Is there a way that Oxygen might be engineered to make this easy to do?

**Comment by louisreingold** [comment] 2019-09-30 00:43
Definitely open to the discussion and suggestions for mega menu functionality. 

But there's nothing fundamental about something being in a separate plugin that would cause performance problems. If the exact same code was inside Oxygen, you'd have the exact same performance.

**Comment by jmcbade** [comment] 2019-09-30 01:46
Ok, so the functionality (not where it's implemented) does effect performance.  So yeah, that kind of "built in" functionality akin to what Max Mega Menus provides is we feel a worthy discussion.

I would agree with others that the mobil menus layout is maybe less "robust" or appealing than the way Mega Menu does it.  I also appreciate that in any development process, priorities must be considered.  So if performance wise there is not difference if the menu is add with a plugin or, inherent, for now the plugin method seems acceptable.

For us as users of Oxygen, there is an advantage in time and effort if the functionality is included in Oxygen as we would likely spend less time going back and forth, but it's not a "deal breaker" given your explanation.

Thanks.

**Comment by ThePopularizer** [comment] 2019-09-30 23:21
> megamenu type functionality native in Oxygen would be desirable and useful? Is there a way to do this now? 

Here's one way to do it natively within Oxygen with just CSS: 

![Watch the video](https://media.giphy.com/media/Qy7Z2MKSdoe7ftu5DF/giphy.gif)

You'll needo add "mega-menu" class to the top-level menu.

Here is the CSS: 

`.oxy-header-wrapper .oxy-header-row .oxy-nav-menu:not(.oxy-nav-menu-open) #menu-main > .mega-menu > .sub-menu {
left: 0;
width: 100%;
}
.oxy-header-wrapper .oxy-header-row .oxy-header-container {
position: relative;
}
.oxy-header-wrapper .oxy-header-row .oxy-nav-menu:not(.oxy-nav-menu-open) .mega-menu {
position: initial;
}
.oxy-header-wrapper .oxy-header-row .oxy-nav-menu:not(.oxy-nav-menu-open) .mega-menu .sub-menu {
display: flex;
flex-direction: row;
}
.oxy-header-wrapper .oxy-header-row .oxy-nav-menu:not(.oxy-nav-menu-open) .mega-menu .sub-menu li {
flex: 1;
}
.oxy-header-wrapper .oxy-header-row .oxy-nav-menu:not(.oxy-nav-menu-open) .mega-menu:hover > .sub-menu > .menu-item > .sub-menu {
display: inline-block;
position: relative;
left: 0;
opacity: 1;
visibility: visible;
}
.oxy-header-wrapper .oxy-header-row .oxy-nav-menu:not(.oxy-nav-menu-open) .mega-menu > .sub-menu > .menu-item .sub-menu {
font-size: 14px;
border-top: 1px solid rgba(0,0,0,0.15);
} /* Optionally format submenu */
.oxy-nav-menu.oxy-nav-menu-dropdowns.oxy-nav-menu-dropdown-arrow:not(.oxy-nav-menu-open) .mega-menu .sub-menu .menu-item-has-children > a:after {
transform: rotate(135deg);
} /* Rotate the little arrow downwards */`

The [original Facebook thread](https://www.facebook.com/groups/1626639680763454/permalink/2054576127969805/).

**Comment by Kpudlo** [comment] 2023-06-28 03:41
Closing as a duplicate of #928.

**Closed by Kpudlo** 2023-06-28 03:41 UTC
Labels: enhancement, Element - New - Mega Menu, Feature Implemented in Composite Elements
