### ISSUE TITLE
Meta Box Advanced Image in a cloneable group always gets thumbnail size in repeater

### ISSUE THREAD

**Issue by frozenwind85** [soflyy/oxygen-bugs-and-features#2776] opened 2022-03-04 21:24 UTC
Advanced Image of Meta Box works fine if not in a cloneable group with repeater. Oxygen gives options like image size to choose.
But in a cloneable group and repeater, it always output a thumbnail size image. When selecting the image field in the repeater group selection, oxygen does not give any options like image size.

1. In Meta Box, create a custom field for a post/page.
2. In the custom field, create a cloneable group. Add an advanced Image sub field to the group.
3. Create a post/page with the custom field. Add an image to the Advanced Image field.
4. Edit the post/page in oxygen. Add a repeater for the cloneable group.
5. Add an image block. Set the data to the Advanced Image field of the repeater group.
6. In frontend, check the image. It is always the thumbnail size, like the screenshot below.

![image](https://user-images.githubusercontent.com/30331116/156843390-6b66f81c-90d1-4146-ad70-d782b5a66998.png)

**Comment by KittenCodes** [comment] 2022-03-05 08:05
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2546

**Closed by KittenCodes** 2022-03-05 08:05 UTC
Labels: bug
