### ISSUE TITLE
Unit inheritance overrides filled values

### ISSUE THREAD

**Issue by maxmeelay** [soflyy/oxygen-bugs-and-features#3497] opened 2024-01-22 15:12 UTC
The first section was done with 4.7.1, and after the update to 4.8, this no longer works properly. After “Tweak: Improved unit/value inheritance on breakpoints (#4352)” breakpoints with not touched units are updated with upper breakpoint unit and the layout is getting broken. The same issue we have if we edit a lower breakpoint and input the value of px only - when we go back to the upper breakpoint and change the unit, the unit of the previously edited breakpoint changes also. You cant change the unit of already filled fields because if there was displayed px and was filled out it means it should stay in px. We have dozens of websites with thouseds of styles done this way, the fallback for it is urgent and necessary because we cannot update sites either of our clients.

The sandbox instance URL: http://oxy-sandbox.you2.pl/

![image (4)](https://github.com/soflyy/oxygen-bugs-and-features/assets/95044326/4640d8af-9684-4e70-85fd-ef24e7d52a7d)
![image (3)](https://github.com/soflyy/oxygen-bugs-and-features/assets/95044326/b153f25e-71c1-4568-8259-7b1352aa8b85)

**Comment by Spellhammer** [comment] 2024-01-22 15:53
Thanks for the report! Closing this as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3490.

This is under investigation.

**Closed by Spellhammer** 2024-01-22 15:53 UTC
Labels: bug
