### ISSUE TITLE
[2.2.1] Defining button:<state> throws error message

### ISSUE THREAD

**Issue by ascripter** [soflyy/oxygen-bugs-and-features#172] opened 2019-03-21 11:59 UTC
**Describe the bug**
On a plain page, adding a button element and then adding styles for any state of the button (tested with hover, active, before, after) raises an error when displaying the rendered page, i.e.:

"""
Notice: Undefined index: button-color in /var/www/web56/htdocs/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2762

Notice: Undefined index: button-text-color in /var/www/web56/htdocs/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2763
"""

I need to define the mentioned attributes explicitly to make the error disappear. However the button itself works as it should.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Can't replicate it. In the sandbox no error appears.

**Expected behavior**
No error message - because the button itself works as it should.

**What actually happens**
Error message that seems not relevant.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/8597615/54750743-0aa3bc80-4bd9-11e9-94a7-5bf0923ce80b.png)

**Desktop (please complete the following information):**
Win10
Firefox 65.0.2
Oxygen 2.2.1

**Comment by KittenCodes** [comment] 2019-08-09 14:54
Replicated in 2.4.1.

**Comment by DeepMedia-Joshua** [comment] 2020-04-18 09:52
**Describe the bug**
I have the issue both front end and backend. I am not sure how much of "issue" it actually is as the notice only appears when define('WP_DEBUG', false), define('WP_DEBUG_LOG', false) and define('WP_DEBUG_DISPLAY', false) are set to "true". **The notice is also only displayed when activating the WooCommerce Integration** - I thought that information might help.

The issue is that if WP_DEBUG, WP_DEBUG_LOG and WP_DEBUG_DISPLAY are truly in the config file - you can't access Oxygen from the WP navigation bar on the left. I have to remove the notices using the inspector panel and then I can select the option I would like to use - only to have the same issue once the page loads. 

**Have you tried all the steps at** https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?
Yes.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I have not tried - figured that if the bug is still open it obviously can't be replicated. **Important:** How I achieve the notice is by implementing a fresh install with oxygen and then simply adding the Woo Commerce Integration. Upon activation of the WooCommerce Integration the notice is generated. 

**Expected behavior**
No error message - because the button itself works as it should.

**What actually happens**
Error message that seems not relevant.

**Screenshot**
https://paste.pics/37641f2f07e8f6008e8de689146c627a

**System**
MacOS (Not sure if this is important)?
Safari 13.1
Oxygen 3.2
WooCommerce Add-on 1.2

**Comment by KittenCodes** [comment] 2020-04-18 11:41
#974

**Comment by KittenCodes** [comment] 2020-11-25 16:38
Fixed in v3.6.

**Closed by KittenCodes** 2020-11-25 16:38 UTC
Labels: bug, confirmed bug
