### ISSUE TITLE
More breakpoints

### ISSUE THREAD

**Issue by joomapp** [soflyy/oxygen-bugs-and-features#2565] opened 2021-12-09 20:32 UTC
**Describe the feature you'd like to see included in Oxygen.**
*Now (v 3.9) Oxygen has 4 breakpoints where the largest one serves screens from 1200 and up. With the new era of widescreen 2500 and 3400 are starting to become quite normal.*

**What are the use cases for this feature?**
*Font sizes/marins are now limited to the 1200 and up but these are too small for 3400 screens*

**Examples of this feature or functionality.**
*None, Oxygen will be the first one*

**Comment by shoelaced** [comment] 2022-01-11 00:14
Pleeeeeaaaaaasseeeee add like 3 more breakpoints. Better yet let us just add however many we want. I'm *constantly* adding entire new stylesheets just to manually write media queries.

**Comment by Kpudlo** [comment] 2022-07-27 16:11
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/700

**Closed by Kpudlo** 2022-07-27 16:11 UTC
Labels: enhancement
