### ISSUE TITLE
Set font-family with fallback

### ISSUE THREAD

**Issue by flore89** [soflyy/oxygen-bugs-and-features#2704] opened 2022-01-20 08:40 UTC
**Describe the feature you'd like to see included in Oxygen.**
Hello, I think it should be possible to set a font-family with fallback options or it should do it automaticly in the oxygen builder settings. So instead of: font-family: 'IBM Plex Sans'; -> font-family: 'IBM Plex Sans', Helvetica, Arial, sans-serif;

**What are the use cases for this feature?**
This bug brought me to it:
http://clagnut.com/blog/2377
https://stackoverflow.com/questions/11888586/shy-soft-hyphen-and-chrome-and-safari)

**Comment by Kpudlo** [comment] 2023-04-19 13:24
Duplicate of #990

**Closed by Kpudlo** 2023-04-19 13:24 UTC
Labels: enhancement
