### ISSUE TITLE
Unable to Open "Where does this template apply?" Options

### ISSUE THREAD

**Issue by nataliamesquita** [soflyy/oxygen-bugs-and-features#3599] opened 2024-11-19 20:27 UTC
![Captura de tela 2024-11-19 172451](https://github.com/user-attachments/assets/66ce3aa2-300a-499c-bf09-1cfeeea4c4f8)

When attempting to click on the options under "Where does this template apply?" in the Oxygen Builder, the options do not expand or open. This issue prevents selecting specific template application settings.

----

Steps to Reproduce:

Open the template settings in Oxygen Builder.
Locate the "Where does this template apply?" section.
Click on the section to expand or select options.

---

Expected Behavior: The section should open to display options for template application settings (Singular, Archive, Other).

Actual Behavior: Clicking on the section has no effect, and the options do not expand.

---

Console Errors: The browser console shows the following errors:

Failed to load resource: the server responded with a status of 403
Uncaught ReferenceError: Search is not defined
wp.compose.withState is deprecated since version 5.8
Unchecked runtime.lastError: The message port closed before a response was received

**Comment by Kpudlo** [comment] 2024-11-19 21:26
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3592 and fixed in Oxygen 4.9.1. RC 1, which has the fix to address this issue. You can download this version of Oxygen by logging into the [Oxygen Customer Portal](https://oxygenbuilder.com/portal/) and navigating to the [Beta Access](https://oxygenbuilder.com/beta-access/) page.

**Closed by Kpudlo** 2024-11-19 21:26 UTC
Labels: bug
