### ISSUE TITLE
WPML - OXYGEN - SUPPORT

### ISSUE THREAD

**Issue by davidperroud** [soflyy/oxygen-bugs-and-features#3049] opened 2022-08-11 11:25 UTC
**Describe the feature you'd like to see included in Oxygen.**
Official support between Oxygen and WPML

**What are the use cases for this feature?**
Full multilinguish e-commerce websites

**Comment by Kpudlo** [comment] 2022-08-16 01:51
Duplicate of #938

**Closed by Kpudlo** 2022-08-16 01:51 UTC
Labels: enhancement
