### ISSUE TITLE
'Dynamic Data > PHP Function' in template doesn't render if more than one level of inheritance

### ISSUE THREAD

**Issue by wallenstone** [soflyy/oxygen-bugs-and-features#3067] opened 2022-08-29 15:48 UTC
**Describe the bug**
If a template contains dynamic data using a PHP function return value, the return value does not populate on the frontend if the displayed page uses a template that does not directly inherit the template containing the dynamic data element. The data still populates in the builder, however.

EXAMPLE:  Template A contains the dynamic element > Template B inherits Template A > Template C inherits Template B and applies to all archives.  Archive pages will not show the dynamic data.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
Issue shown here:  https://oxygen-qyrl8wxgv2pnl.oxygen-demo.qsandbox.me/blog/
Compare to:  https://oxygen-qyrl8wxgv2pnl.oxygen-demo.qsandbox.me/

The header builder of the sandbox contains a text element with the date dynamically populated using the PHP 'date' function. It displays properly on the home page, but is empty on the archive page.

**Comment by Spellhammer** [comment] 2022-08-30 16:04
I believe this is a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1881.

**Closed by Spellhammer** 2022-08-30 16:04 UTC
Labels: bug
