### ISSUE TITLE
Google Maps not working

### ISSUE THREAD

**Issue by rockymedia** [soflyy/oxygen-bugs-and-features#2196] opened 2021-05-26 09:51 UTC
Google Maps is not working any more:
https://oxygen-q2g48awm5zyfl.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true

Down on all sites...

**Comment by ehni** [comment] 2021-05-26 09:56
Official oxygen maps component (see also for example https://bnb.oxy.host/contact/) is broken due to google maps v2 deprecation.

Official note from Google: https://developers.google.com/maps/documentation/javascript/v2tov3

Workaround:
1. Open Google Maps
2. Select your desired location
3. Open "Share" menu
4. Select "Embed" and copy iframe code into a oxygen code block element php/html section

**Comment by techjase** [comment] 2021-05-26 10:08
+1

**Comment by zbyneksmetana** [comment] 2021-05-26 12:41
Not working on my all websites

**Comment by BrunoPirard** [comment] 2021-05-26 13:06
+1

**Comment by KittenCodes** [comment] 2021-05-26 13:45
​This is caused by Google removing support for their v2 API as of the 26th May 2021. Our development team are investigating and we hope to have a fix for the issue shortly.
​
​In the mean-time, you can search for your location in Google Maps, click the share icon and get an embed code that can be used in a Code Block in Oxygen.

**Comment by kirkdave** [comment] 2021-05-26 15:09
> The Maps JavaScript API v2 is deprecated as of May 19, 2010, and will be turned off on May 26, 2021. As a result, your site's v2 maps will stop working, and will return JavaScript errors. To avoid any inconvenience, we strongly recommend migrating your site to the Maps JavaScript API v3 before May 26, 2021.

If only there had been some notice...

**Comment by Spellhammer** [comment] 2021-05-26 16:43
Google maps fixed in 3.8 RC 2: https://oxygenbuilder.com/2021/05/26/oxygen-3-8-release-candidate-2-now-available/

**Closed** 2021-05-26 16:43 UTC
Labels: bug, confirmed bug
