### ISSUE TITLE
Repeater element on posts archive pages only shows content on 1st page

### ISSUE THREAD

**Issue by amiegrrl** [soflyy/oxygen-bugs-and-features#3548] opened 2024-07-26 19:56 UTC
Hi, I have run to an issue with repeater elements + post archive pages. 

I was able to reproduce it in a [sandbox here]( https://oxygen-qn2nhr9qh3wzl.oxygen-demo.qsandbox.org/blog/category/uncategorized)

Example is with category archive page. 1st page you will see recent posts and below the pagination a repeater element, as a slider with images. Go to second page of pagination, and the data no longer shows for the repeater element's content. 
Repeater element is using ACF custom post type + featured image field for data, if that makes a difference.

any help much appreciated.

**Comment by Kpudlo** [comment] 2024-07-30 13:46
Duplicate of/Same request as https://github.com/soflyy/oxygen-bugs-and-features/issues/1254

**Closed by Kpudlo** 2024-07-30 13:46 UTC
Labels: bug
