### ISSUE TITLE
Add sort order by option of RANDOM to easy posts query setting.

### ISSUE THREAD

**Issue by waptug** [soflyy/oxygen-bugs-and-features#1088] opened 2020-04-30 06:41 UTC
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**Add the option to the sort by in easy post for "random" so every time the page gets refreshed the sort order of the returned posts are random and different**

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
**On sites with lots of posts this will display some that may not get looked at all the often like in a membership directory to show case a member post on an archive page by category.** 

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

I am seeing some attempts at this and some plugins have come close to doing this but they all seem to lack the ability to integrate with easy post to control the output.

**Comment by KittenCodes** [comment] 2020-12-31 17:46
Duplicate of #1003

**Closed by KittenCodes** 2020-12-31 17:46 UTC
Labels: Element - Easy Posts/Repeater, enhancement
