### ISSUE TITLE
add rand function repeater element

### ISSUE THREAD

**Issue by dogoman78** [soflyy/oxygen-bugs-and-features#1487] opened 2020-08-26 19:24 UTC
**Describe the feature you'd like to see included in Oxygen.**
for repeater element / Query / order
Add rand function

**What are the use cases for this feature?**
For rand function, several times you just want to display elements in a random way to make your page more dynamic

**Examples of this feature or functionality.**

For displaying several products in a limited space with a random function

*If another product has done it well, provide examples here.*

**Comment by KittenCodes** [comment] 2020-12-31 17:46
Duplicate of #1003

**Closed by KittenCodes** 2020-12-31 17:46 UTC
Labels: Element - Easy Posts/Repeater, enhancement
