### ISSUE TITLE
Background images in Gutenberg editor aren't editable

### ISSUE THREAD

**Issue by stephde123** [soflyy/oxygen-bugs-and-features#3332] opened 2023-06-12 13:26 UTC
**Describe the bug**
An Editor can't change every background image in the Gutenberg editor.
There is a Div with a background image that is not editable.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qr9hh2dg3ywsl.oxygen-demo.qsandbox.org/test/

**Steps required to reproduce the bug:**
1. Go to https://oxygen-qr9hh2dg3ywsl.oxygen-demo.qsandbox.org/test/
2. You can see 2 background images.
3. Login as Editor (I created an account for that)
4. Go to the [edit page](https://oxygen-qr9hh2dg3ywsl.oxygen-demo.qsandbox.org/wp-admin/post.php?post=16&action=edit) of that page
5. Try to change the second background image
6. See that there is only the possibility to change 1 background image at all.

**Comment by Kpudlo** [comment] 2023-07-19 02:49
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1922 and https://github.com/soflyy/oxygen-bugs-and-features/issues/2290

**Closed by Kpudlo** 2023-07-19 02:49 UTC
Labels: duplicate
