### ISSUE TITLE
Pro menu: mobile dropdowns open page instead toggle sub menu on iPhone

### ISSUE THREAD

**Issue by SpeedyWebPL** [soflyy/oxygen-bugs-and-features#932] opened 2020-03-30 15:57 UTC
**Describe the bug**
Click on link who has children on mobile open page instead toggle sub menu on iPhone. I tried in Safari and Chrome (same problem). On Android everything works fine.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes*
https://oxygen-qvx5cn573vs8k.oxygen-demo.qsandbox.me/

**To Reproduce**
1. Create menu with submenu items.
2. Add Pro menu on main template.
3. Set dropdown mobile option on "toggle"
4. Open page on iPhone.

**Expected behavior**
Toggle subitems instead go to another page

**Smartphone:**
- OS: iOS 13.4
 - Browser: chrome, safari.
 - Oxygen Version 3.2.1

**Comment by michylee** [comment] 2020-03-31 10:51
Same bug for me with Android (Samsung Note 10+ with Android 10).
Same with Samsung S7 with Android 8.0.0
Sometimes it works regularly, most of the time it doesn't work and only opens the first menu item.

**Comment by shoelaced** [comment] 2020-03-31 13:03
It works for me, but only if the parent menu item is a custom link with # in the href.

Realistically though if the mobile dropdowns are enabled at all, the parent link should be automatically disabled so that it only toggles the dropdown, regardless of what's in the href.

**Comment by michylee** [comment] 2020-03-31 13:33
> It works for me, but only if the parent menu item is a custom link with # in the href.
Yes, it's the same for me. If parent menu has custom link with #, it works perfectly.
But... if you put a complete url it doesn't works also with a custom link (as for normal menus with pages or articles).

**Comment by Spellhammer** [comment] 2020-04-01 09:58
This is the intended functionality.

If the parent link which has sub-menu items has a HREF of #, clicking anywhere on the link will toggle the dropdown.

If the parent link which has sub-menu items has a HREF that is not #, clicking the link text will follow the parent link, and clicking the dropdown icon will toggle the dropdown.

This behavior was settled on because the alternatives are:

1. Make the user click the parent link once to expand the dropdown, and they have to somehow magically know to click the same link again in order to follow it. I don't think any user is accustomed to having to click a button or link twice in order to follow it.

OR

2. Make all parent links unfollowable and instead force them to toggle the dropdown. This is a bad call in my opinion and will cause far more issues than the current behavior.

Both of those alternatives are considerably worse UX than the current behavior in my opinion.

**Comment by SpeedyWebPL** [comment] 2020-04-01 10:18
Sorry @Spellhammer, I described the problem incorrectly. Click toggle icon on iPhone move to another site instead show submenu items. I believe preventDefault doesn't work in this situation.

**Comment by michylee** [comment] 2020-04-01 10:26
@Spellhammer, thanks for your support.
But... the problem is that even if you click on the dropdown icon (and not on the menu text) the submenu items are often inaccessible and you are redirected only to the parent menu url. 
Most of the time, the icon does not activate the drop-down menu. 
Thanks again.

**Comment by shoelaced** [comment] 2020-04-01 11:34
@michylee @Spellhammer Yes, either the icon doesn't work well or it's way too small to be usable on a touchscreen, nor can a user really be expected to know that _'the link part goes a page and the icon part opens the sub-menu'_ given that normal select fields (which is essentially how they function on a touch screen) allow you to click anywhere to toggle the dropdown. To be fair, linking parent items with dropdowns is poor UX in the first place on the designer's part. Do two wrongs make a right? 😆 It seems like whether the parent item leads to its `href` or triggers the dropdown should be incorporated into the current option of enabling or disabling the mobile dropdowns altogether. Frankly, it seems like much poorer UX on the frontend to have users clicking a parent menu item that has a dropdown icon with the expectation of revealing the sub-menu and instead being taken to a page they didn't want, and equally poor UX on the Oxygen side to make designers run to the FB group or search around to figure out why it isn't working and whether there's a workaround. Is there an SEO benefit to one or the other? Honestly I have no idea. But if the default functionality isn't going to follow expectations, then at the very least there should be a note in the builder explaining that, or else there are going to be many more bug reports like this one to weed through.

**Comment by michylee** [comment] 2020-04-01 12:03
Thanks to all for your attention.
Reading the @shoelaced message about the icon, i wanted to give a try, simply increasing the Icons Space (default is 0) on Desktop Dropdowns / Dropdown Icon (using 20 px, for example).
Well, this way the problem seems to be solved!
Let me know if you solve it too, please.
Thank you all.

**Comment by michylee** [comment] 2020-04-01 12:12
@SpeedyWebPL i've modified your demo sandbox: https://oxygen-qvx5cn573vs8k.oxygen-demo.qsandbox.me/
Simply adding 15px to Icons Space (on Desktop Dropdowns / Dropdown Icon).
Try again and... tell us, please! :)

**Comment by SpeedyWebPL** [comment] 2020-04-01 16:01
@michylee unfortunately it's still not work for me (same problem).

**Comment by SpeedyWebPL** [comment] 2020-04-01 16:18
![pro-menu](https://user-images.githubusercontent.com/39051457/78160967-072a4e80-7445-11ea-9201-53a6758f7e38.gif)

**Comment by michylee** [comment] 2020-04-06 09:42
@SpeedyWebPL Another workaround could be this:
On Mobile Menu / Menu Styles:
- Set Item Text Align to Left. 
On Desktop Dropdowns / Dropdown Icon
- try to set Icons Space to auto;
- set Icon Margin left and right to 10 px;
- fingers crossed! :)

**Comment by SpeedyWebPL** [comment] 2020-04-06 11:17
@michylee thanks for your commitment. I tried your tips. However I still have this problem. 

I tried to find the solution on my own, but without success.

**Comment by michylee** [comment] 2020-04-06 12:09
@SpeedyWebPL 
Don't worry about it. I'm going crazy too with the Pro Menu and the submenus that... if i can help others, i'm happy.
In fact... i thought i solved it with the suggestions i gave you but... on another site, i still have the same problem as you. 
And there's no way to solve it.
Same server, same version of PHP, same version of Oxygen Builder (3.2.1).
If there are links in the parent menu and there are submenus, the Pro Menu sometimes becomes totally unusable.

**Comment by Spellhammer** [comment] 2020-05-28 14:33
If anyone can provide environmental information to replicate the "toggling dropdown follows child link" issue, please post it here and I'll be glad to investigate.

So far, I've not been able to replicate this on a real iOS device (iPhone SE) or any mobile device via BrowserStack.

**Comment by acicovic** [comment] 2020-05-31 09:52
For me this happens on and off. I get the following console warning:

/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:3

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

This is probably related as it seems that preventDefault is not always successful, so the event bubbles up and acts differently.

**Comment by acicovic** [comment] 2020-05-31 10:09
On my desktop computer (Windows) the issue doesn't happen in Firefox. But I get the issue on Vivaldi (Chromium derivative based on Chromium 81.0.4044.142) as well as latest Chrome Portable (version Version 83.0.4103.61) from https://portableapps.com/

On Android, I have the issue on Vivaldi and Although I haven't tested, I suspect I would have the same issue in Chrome.

**Comment by Spellhammer** [comment] 2020-07-19 14:35
For anyone experiencing this, please try adding this to a Code Block in your main template or on the page containing the Pro Menu:

```javascript
jQuery('body').on('touchstart click', '.oxy-pro-menu-dropdown-icon, .oxy-pro-menu-dropdown-icon-click-area', function(e) {
  
  jQuery('.sub-menu').css('pointer-events', 'none');
  setTimeout( function() {
    jQuery('.sub-menu').css('pointer-events', 'initial');
  }, 500);
  
})
```

This should fix the problem.

**Comment by acicovic** [comment] 2020-07-19 19:05
@Spellhammer thanks for the input. Is this planned to be merged as a fix into Oxygen anytime soon?

Thanks.

**Comment by KittenCodes** [comment] 2020-11-25 16:26
Fixed in v3.5.

**Closed by KittenCodes** 2020-11-25 16:26 UTC
Labels: bug, confirmed bug

**Comment by hawkeye217** [comment] 2021-08-14 01:44
FYI - for anyone who ends up here wondering why their Pro Menu dropdown is misbehaving, check this link:

https://toolset.wiki/oxygen-pro-menu-entire-parent-toggle-dropdown-not-working/

**Comment by AdilPerformAds** [comment] 2022-11-25 12:49
> https://toolset.wiki/oxygen-pro-menu-entire-parent-toggle-dropdown-not-working/

Link is dead.

**Comment by TZirngibl** [comment] 2024-10-23 01:04
if you type "null" instead of the "#" in the wordpress menu URL, it works as intended.
