### ISSUE TITLE
the eye is no longer working in the editor

### ISSUE THREAD

**Issue by lucianahanan** [soflyy/oxygen-bugs-and-features#3596] opened 2024-11-18 16:17 UTC
WP 6.5.5
PHP 8.1
Oxygen 4.9
no console errors
it's not Hydrogen

The eye is no longer hiding elements in the Editor.

without the eye clicked:
![image](https://github.com/user-attachments/assets/695f34ea-7fc0-4f24-a19d-223552c2b00c)
![image](https://github.com/user-attachments/assets/d568dded-a156-4bbb-bd52-33bc4f4a8d04)

with the eye clicked:
just the purple border disappears, but the element stays there.
![image](https://github.com/user-attachments/assets/5f378432-a7af-4883-a818-474d67ca91d4)
![image](https://github.com/user-attachments/assets/b4fc9b3b-e781-44b1-b5ef-c4531eb0e9f9)

**Comment by Kpudlo** [comment] 2024-11-18 20:53
This is a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3562.

It has been fixed in Oxygen 4.9.1, which is available for Beta testing and can be downloaded from the [Oxygen Customer Portal](https://oxygenbuilder.com/portal/).

**Closed by Kpudlo** 2024-11-18 20:53 UTC
Labels: bug
