### ISSUE TITLE
Social icons element outdated 

### ISSUE THREAD

**Issue by lecmaj** [soflyy/oxygen-bugs-and-features#3516] opened 2024-03-12 13:02 UTC
https://oxygenbuilder.com/documentation/builder-elements/social-icons/

Please update social icons element to replace twitter with X and icon per following media https://about.x.com/en/who-we-are/brand-toolkit

Thank you.

**Comment by Kpudlo** [comment] 2024-04-12 01:31
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3376

**Closed by Kpudlo** 2024-04-12 01:31 UTC
Labels: bug
