### ISSUE TITLE
Using Conditional Settings Removes ID-Specific CSS From Div

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#3233] opened 2023-02-13 22:07 UTC
**Describe the bug**
Using [Conditions](https://oxygenbuilder.com/documentation/other/conditions/) will — in certain cases — prevent ID-specific CSS of the conditional element from being displayed on the frontend.

**Reproduction**
1. Add repeater to template.
2. Add div under repeater-created div.
   1. Add conditional setting.
   2. Add CSS property (i.e width: 100%).

Visit the page that uses the template: Width CSS Property won't be displayed on added div (when it should be).

**Comment by Kpudlo** [comment] 2023-03-04 19:24
Duplicate of #2867.

**Closed by Kpudlo** 2023-03-04 19:24 UTC
Labels: bug
