### ISSUE TITLE
v4.0: Custom CSS garbled (base 64)

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#2901] opened 2022-05-30 17:37 UTC
There is a critical bug affecting upgrade path 3.9 -> 4.0.

Client just contacted us with broken website, turns out custom CSS is garbled (base 64 encoding) after they updated oxygen:

![image](https://user-images.githubusercontent.com/7825147/171039075-ce9f054c-84da-48a1-875f-ffc8ab27120b.png)

**Sandbox:**

Unable to reproduce in sandbox due to the limitations of the sandbox environment. Have posted the issue here in the interests of the community as this is very likely **not** an isolated occurrence.

**Comment by Spellhammer** [comment] 2022-06-01 14:45
We've been unable to reproduce this internally.

Can you provide any more details? What limitations of the Sandbox environment prevent you from reproducing it there?

**Comment by KittenCodes** [comment] 2022-06-10 16:32
Closing. Will re-open if OP replies.

**Closed by KittenCodes** 2022-06-10 16:32 UTC
Labels: bug
