### ISSUE TITLE
PHP Warning:  Undefined variable $old_query in image.class.php on line 209

### ISSUE THREAD

**Issue by adrien-robert** [soflyy/oxygen-bugs-and-features#3191] opened 2023-01-08 17:33 UTC
I'm using Oxygen 4.2 and PHP 8.0

I have this warning:

`PHP Warning:  Undefined variable $old_query in .../wp-content/plugins/oxygen/component-framework/components/classes/image.class.php on line 209`

When I only have an image within my Main template:

![image](https://user-images.githubusercontent.com/4320990/211210189-e50eb350-bc3c-4871-ad6f-5adf25b797dd.png)

I only loaded a svg logo from Media Library and changed the width and height (nothing else):

![image](https://user-images.githubusercontent.com/4320990/211210199-38cce07d-083d-492f-890c-8a5112d95907.png)

This PHP Warning triggers when I load my Main template that include this oxygen image element.

Here's the function "get_attachment_sizes" that causes this PHP Warning (from oxygen/component-framework/components/classes/image.class.php file):

```
function get_attachment_sizes() {
	if ( isset($_REQUEST['action']) && $_REQUEST['action'] == "ct_get_attachment_sizes") { 
		$nonce  	= $_REQUEST['nonce'];
		$post_id 	= intval( $_REQUEST['oxy_post_id'] );
		$attachment_id 	= stripslashes($_REQUEST['oxy_attachment_id']);

		// check nonce
		if ( ! isset( $nonce, $post_id ) || ! wp_verify_nonce( $nonce, 'oxygen-nonce-' . $post_id ) ) {
			// This nonce is not valid.
			die( 'Security check' );
		}

		// check user role
		if ( ! oxygen_vsb_current_user_can_access() ) {
			die ( 'Security check' );
		}

		$options = file_get_contents('php://input');
		$options = json_decode( $options, true );

		if ( $options ) {

			global $oxy_vsb_use_query, $oxygen_vsb_components;
			
			$old_query = false;

			if($oxy_vsb_use_query) {
				$old_query = $oxy_vsb_use_query;
			}

			$query = $oxygen_vsb_components['repeater']->setQuery($options);
		
			$oxy_vsb_use_query = $query; //$this->query;
			
			if ($query->have_posts()) {
				$query->the_post();
			}
		
		}

		// sign "[oxygen]" shortcode on the fly
		if (stripos($attachment_id, '[oxygen') !== false) {
			$attachment_id = ct_sign_oxy_dynamic_shortcode(array($attachment_id));
		}

		$attachment_id = intval(do_shortcode($attachment_id));
		
		$args = array(
			'p'         => $attachment_id,
			'post_type' => 'attachment'
		);
		$image_query = new WP_Query($args);
		if( !$image_query->have_posts() || count( $image_query->posts ) != 1 ) {
			$json = json_encode( array("error" => __("Image not found", "oxygen")) );
		}
		else {
			$attachment = wp_prepare_attachment_for_js( $image_query->posts[0] );
			
			// full size doesn't exist in wp_get_attachment_metadata(), save it to add later
			$full = array();
			if ( isset( $attachment['sizes']['full'] ) ) {
				$full = array(
					'full' => $attachment['sizes']['full']
				);
			}
			
			// get sizes available for this particular attachment
			$meta_data = wp_get_attachment_metadata( $attachment_id );
			if ( isset( $meta_data['sizes'] ) && is_array( $meta_data['sizes'] ) ) {
				
				$attachment_url = wp_get_attachment_url( $attachment_id );
				$base_url       = str_replace( wp_basename( $attachment_url ), '', $attachment_url );

				// generate URLs from filenames (taken from wp_prepare_attachment_for_js())
				foreach ( $meta_data['sizes'] as $size_name => $size_data) {
					$meta_data['sizes'][$size_name]['url'] = $base_url . $size_data['file'];
				}
				
				$attachment['sizes'] = array_merge( $full, $meta_data['sizes'] );
			}
			$json = json_encode( $attachment['sizes'] );
		}

		// reset query to previous state
        if($old_query) {
            
            $oxy_vsb_use_query = $old_query;

            $oxy_vsb_use_query->reset_postdata();
        }

		header('Content-Type: application/json', true, 200);
		echo $json;
		die();
	}
}
```
	
The issue is on the line after the comment: "// reset query to previous state "
This line: "if($old_query) {"

And you're only declaring the $old_query variable inside the "if ($options)" statement, which would not always be true.

The fix is to add "$old_query = false;" above the "if ( $options ) {" statement.

Please fix it for Oxygen 4.4 @Spellhammer 

Here is the updated code: https://gist.github.com/adrien-robert/fc6c2535dcbf29f6960a92d9bcf74d01

**Comment by Kpudlo** [comment] 2023-01-20 20:47
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3172

**Closed by Kpudlo** 2023-01-20 20:47 UTC
Labels: bug
