### ISSUE TITLE
header builder column optioins

### ISSUE THREAD

**Issue by DeeJayAlex** [soflyy/oxygen-bugs-and-features#3572] opened 2024-09-27 22:45 UTC
why can we not have the header builder with one, two or more columns.  Why always three.  Can we make this editable.  I am sure you have been asked this before, but I searched the internet and it seems is a highly requested feature.  Please add

**Comment by Kpudlo** [comment] 2024-09-28 17:07
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/190

**Closed by Kpudlo** 2024-09-28 17:07 UTC
Labels: enhancement
