### ISSUE TITLE
Oxygen WooCommerce 2.0 calls for Undefined property: stdClass::$name after install 

### ISSUE THREAD

**Issue by jevgen** [soflyy/oxygen-bugs-and-features#3301] opened 2023-05-14 07:49 UTC
**Describe the bug**
Oxygen WooCommerce 2.0 calls for Undefined property: stdClass::$name after install 

1. Install Oxygen on a WooCommerce site, with Oxygen WooCommerce 2.0 integration
2. Install Query Monitor
3. Scroll down to Query Monitor > 'PHP Errors'
4. See error Undefined property: stdClass::$name

wp-content/plugins/oxygen-woocommerce/admin/includes/updater/EDD_SL_Plugin_Updater_Oxygen_WooCommerce.php:86
EDD_SL_Plugin_Updater_Oxygen_WooCommerce->check_update()
wp-includes/class-wp-hook.php:310
apply_filters('pre_set_site_transient_update_plugins')
wp-includes/option.php:2036
set_site_transient()
wp-includes/update.php:391
wp_update_plugins()
wp-includes/update.php:1020
_maybe_update_plugins()
wp-includes/class-wp-hook.php:308
do_action('admin_init')
wp-admin/admin.php:175

**Comment by Kpudlo** [comment] 2023-06-28 03:22
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2009

**Closed by Kpudlo** 2023-06-28 03:22 UTC
Labels: bug
