### ISSUE TITLE
Dynamic data background-image does not appear to work for pseudo elements

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#3324] opened 2023-06-02 20:47 UTC
**Describe the bug**

Dynamic data background-image does not appear to work for pseudo elements.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

https://oxygen-qgqk5s39dqrsl.oxygen-demo.qsandbox.org/hello-world/

**Comment by Kpudlo** [comment] 2023-07-19 02:39
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2171

**Closed by Kpudlo** 2023-07-19 02:39 UTC
Labels: bug
