### ISSUE TITLE
Make it easier to see which pages use Oxygen or Gutenberg frontend and backend

### ISSUE THREAD

**Issue by guyinpv** [soflyy/oxygen-bugs-and-features#3053] opened 2022-08-12 17:11 UTC
**Describe the feature you'd like to see included in Oxygen.**
When browser pages in the WP backend, tag the listing whether the page is edited in Oxygen or Gutenberg.
I have sites where not every page needs to be Oxygen since they are simple paragraphs and images and might be easier for clients to edit that way. But more complex pages use Oxygen. There is no way to tell when looking at page listings whether I should open the WP backend, or open Oxygen.

**What are the use cases for this feature?**
If a page is Oxygen, I don't want users opening Gutenberg and typing stuff, and vice versa. 
If they don't know whether the page is Gutenberg or Oxygen, they have to just pick on and see if they were right before switching to the other. It wastes time.

**Examples of this feature or functionality.**
Here is how Divi tags pages:
![divi marks posts](https://user-images.githubusercontent.com/708955/184408405-be5dc610-f1ae-4f92-bc32-ac8603c705ef.png)

There is similar issue from the frontend. If the page is Oxygen, I can hover over the WP admin bar and click "Edit in Oxygen". If it's not an Oxygen page, it changes to "Edit template....". I don't want users accidentally trying to edit a template because they have muscle memory clicking whatever is the first thing in the Oxygen menu dropdown.
Further, if Oxygen detects it is open in another tab, the link disappears entirely sometimes, making it very unclear whether it's an Oxygen page or Gutenberg.
What I want is a simple _one click to edit content_, whether it's Oxygen or Gutenberg, it needs to be clear and obvious which has control of the page. And just because Oxy is open in another tab, the menu link shouldn't disappear entirely, just stick to the popup warning or something, because Oxygen is often wrong that it's still open somewhere, it usually isn't. For example if I'm editing a page in Oxygen, and then I click on my header, I'm given a link to open the template, but when I click that, the next page gives a warning that Oxygen is already open, which it isn't because I just left that page to go into the template!

I feel that all around these various Oxygen links and edit buttons are just not a smooth experience, especially when pages are controlled by both Gutenberg and Oxygen. And how much more tricky does it get if we use the Gutenberg plugin, or make the Oxygen page editable in Gutenberg? That's like 4 possibilities how/where to edit our content, and we have no real obvious way to know where to go to edit when in the frontend or the backend.

**Comment by Kpudlo** [comment] 2022-08-30 03:47
Duplicate of #1878

**Closed by Kpudlo** 2022-08-30 03:47 UTC
Labels: enhancement
