### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Facidmx** [soflyy/oxygen-bugs-and-features#2316] opened 2021-07-22 22:38 UTC
Hello everybody I am new with oxygen and i have a very rookie question, im on charge of a online store and the searchbar stopped working when you look for something it just gives me a white page everithing on the store works except for the searchbar and i donkt know how to fix it

**Comment by jamescrabb** [comment] 2021-07-23 07:31
You need a search results template

**Comment by KittenCodes** [comment] 2021-07-23 14:14
This is caused by an issue in the latest WooCommerce update and will need to be fixed by the WooCommerce team themselves. It seems that it's affecting lots of sites - not just Oxygen sites.

There's more information on the WooCommerce GitHub here: https://github.com/woocommerce/woocommerce/issues/30298.

I've tried the fix linked below and it has resolved the issue on several sites. Please try the same on your site:

https://diviengine.com/woocommerce-5-5-1-issue-with-divi-search/

The fix requires you to download the file from the above link and use that file in place of the existing \wp-content\plugins\woocommerce\includes\class-wc-query.php file.

**Closed by KittenCodes** 2021-07-23 14:14 UTC
