### ISSUE TITLE
Metabox Settings Page CLonable Group No Content

### ISSUE THREAD

**Issue by orestismammis** [soflyy/oxygen-bugs-and-features#3021] opened 2022-07-24 12:18 UTC
https://oxygen-qdwrj544xyc8.oxygen-demo.qsandbox.me/product-tour/

No images shown, no headlines shown, everything done by the book.
Settings Page, Custom fields for Settings page
Oxygen Repeater, Metabox Group = no results

SANDBOX:
https://oxygen-qdwrj544xyc8.oxygen-demo.qsandbox.me/product-tour/

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by pedrostein** [comment] 2022-09-16 12:05
I came across this issue as well, fortunately in my case I could use a reusable part. 

But in case of a handover to a client it would be real great if this would work, so they would have a single source for updating site-wide changes / updates

**Comment by Kpudlo** [comment] 2022-10-23 03:05
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2669

**Closed by Kpudlo** 2022-10-23 03:05 UTC
Labels: bug

**Comment by ribenawrath** [comment] 2024-05-03 13:05
I've been trying to get oxygen to fix this for years and it keeps falling on deaf ears. They built the quick switch panel but haven't fixed this yet? I have a Metabox LTD I can't use because of this
