### ISSUE TITLE
Lottie files

### ISSUE THREAD

**Issue by PampoenKoekie** [soflyy/oxygen-bugs-and-features#3491] opened 2024-01-16 07:36 UTC
Good day! I would like to suggest a quicker way to implement Lottie files. Not that it is impossible to implement but please consider putting a quicker implementation of it in the software. It would just make life so much easier; I use it a lot. What would be nice is a button in the HELPER section in the menu, to place the Lottie file in a div or wherever we need it, then have some extra settings such as the file URL to the JSON, either local or web. Also, some play settings, loop etc... Not sure if it would be possible to choose if you want to host the Lottie player locally or use the web version via URL... This would be such a great addition, please consider it. Lottie files are amazing, and this would make your software extend its reach. I host my Lottie Player and files myself, but to place the scripts each time, doing the imports etc is just unnecessary, this could be an awesome change and hope to hear from you soon. Keep well and all the best.

**Comment by Kpudlo** [comment] 2024-01-16 09:28
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1133

**Closed by Kpudlo** 2024-01-16 09:28 UTC
Labels: enhancement
