### ISSUE TITLE
Template application options don't work with Wordpress 6.7

### ISSUE THREAD

**Issue by graphicdetail** [soflyy/oxygen-bugs-and-features#3598] opened 2024-11-19 20:16 UTC
Having updated to Wordpress 6.7, go to "Oxygen > Templates" and click on any template to edit it, or add a new template.

Then under "Where does this template apply?", click on any of the options ("Singular", "Archive" or "Other") - None of them will open.

Rolling back to Wordpress 6.6.2 fixes the issue.  Oxygen needs to be fixed to be compatible with Wordpress 6.7.

**Comment by Kpudlo** [comment] 2024-11-19 21:26
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3592 and fixed in Oxygen 4.9.1. RC 1, which has the fix to address this issue. You can download this version of Oxygen by logging into the [Oxygen Customer Portal](https://oxygenbuilder.com/portal/) and navigating to the [Beta Access](https://oxygenbuilder.com/beta-access/) page.

**Closed by Kpudlo** 2024-11-19 21:26 UTC
Labels: bug
