### ISSUE TITLE
Global color in Toggle Helper doesn't work (2.1.2)

### ISSUE THREAD

**Issue by adrien-robert** [soflyy/oxygen-bugs-and-features#16] opened 2019-01-17 06:45 UTC
Bug Oxygen 2.1.2: I can't use Global color in Toggle Helper element. It doesn't work in the icon color parameters (default, closed and expanded state).

It ouput the number of the global color in value of background-color (see image below) instead of the hexadecimal value.

Can it be fixed soon please?

Here is a blank install where you can see the issue: http://helpless-whale.w5.wpsandbox.pro?upass=iuA3W367UwNl

The page where you can inspect the code to see the bug: http://helpless-whale.w5.wpsandbox.pro/issue-global-color-on-toggle-helper-element/

![image](https://user-images.githubusercontent.com/4320990/51300325-c9056280-1a2b-11e9-8e5a-7abae916a9ad.png)

**Comment by Spellhammer** [comment] 2019-01-31 13:03
Replicated and reported at soflyy/oxygen#1394.

**Comment by Senfti123** [comment] 2019-02-10 11:20
Unfortunately still in 2.2 RC1 :/

**Comment by alpabuz** [comment] 2019-05-03 13:11
Still not fixed. I hope it will be fixed soon

**Comment by adrien-robert** [comment] 2019-05-03 13:52
Yeah need to be fixed pls

**Comment by shoelaced** [comment] 2020-02-17 19:52
Still seeing this issue in 3.1.1

**Comment by sunnyt7** [comment] 2020-04-16 21:35
Still an issue in 3.3 beta :|

**Comment by yankiara** [comment] 2020-04-30 21:14
Come on, what's taking so long???

**Comment by gleysen** [comment] 2020-07-18 13:37
Still an issue in 3.4

**Comment by louissoccard** [comment] 2020-10-03 13:38
Still an issue in 3.5

**Comment by Dafnie** [comment] 2020-11-16 13:48
The problem is that the css property is **background-color: color(6);** - The SCSS is not translated to CSS in frontend.
This should be easy to fix. :-)

.oxy-expand-collapse-icon::before, .toggle-2360 .oxy-expand-collapse-icon::after {
      background-color: color(6);
}

**Comment by KittenCodes** [comment] 2021-04-29 14:15
Fixed in v3.8 Beta 1.

**Closed by KittenCodes** 2021-04-29 14:15 UTC
Labels: bug, confirmed bug

**Comment by adrien-robert** [comment] 2021-04-29 20:15
I can breathe again, thank you :D!
