### ISSUE TITLE
Video element: “Preview image” to properly lazy load YouTube & Vimeo videos (iframe is only loaded on thumbnail click)

### ISSUE THREAD

**Issue by simo8857** [soflyy/oxygen-bugs-and-features#3340] opened 2023-06-22 11:53 UTC
Dear Oxy-team
as you always talk about your great speed and focus on users and development, i'm writing to you with a request of an essential feature. To me, this is a must feature on a modern website. but let me know if you agree.

We need a feature to load only (a custom thumbnail-) image with button, until the user click. First then Oxygen should be allowed to call Youtube for files and display the video. This will improve speed on youtube embeds, and let people let great results, also when a youtube video is on the page. 

BricksBuilder already have this feature - where at you guys?
Bricks builder version 1.7.2 NEW : Video element: New “Preview image” setting to properly lazy load YouTube & Vimeo videos (iframe is only loaded on thumbnail click) -> https://bricksbuilder.io/changelog/#7240

Will you please add this to a comming release. It would improve soooo many sites and page speeds in the community. And hlep people to know you still care about users, development and great simple solutions.

**Comment by Kpudlo** [comment] 2023-08-18 21:56
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/750.

**Closed by Kpudlo** 2023-08-18 21:56 UTC
Labels: enhancement
