### ISSUE TITLE
Testimonial images don't have alt text

### ISSUE THREAD

**Issue by KaitlynAtSymphysis** [soflyy/oxygen-bugs-and-features#2953] opened 2022-06-20 21:28 UTC
Images in testimonials do not show alt text on the front end or have the option to add alt text.

https://oxygen-qhpdcycc9dpml.oxygen-demo.qsandbox.me/sample-page/

**Comment by Spellhammer** [comment] 2024-04-28 12:44
Closing as duplicate of #2225

**Closed by Spellhammer** 2024-04-28 12:44 UTC
Labels: bug
