### ISSUE TITLE
Mobile-first media queries

### ISSUE THREAD

**Issue by MaximeStarssed** [soflyy/oxygen-bugs-and-features#3475] opened 2023-12-21 16:29 UTC
**Describe the feature you'd like to see included in Oxygen.**

Hello, if it's possible, I'd like there to be a redesign of the medias query in css to put the priority on mobile first.

Oxygen uses medias queries like "(max width: 1023px)" and could use "min width" to better adapt to small screens.
With this new practice, site builders more often start with the mobile version and end with the deskop version.
Here's an article that might help Oxygen support implement this: [https://www.sitepoint.com/introduction-mobile-first-media-queries/](https://www.sitepoint.com/introduction-mobile-first-media-queries/)

**Benefit:** better performance and reduced code for search engine crawlers (which scan on mobile first).

_**Thank you if this can be implemented.**_

**Comment by Kpudlo** [comment] 2023-12-26 23:26
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3475 and https://github.com/soflyy/oxygen-bugs-and-features/issues/126

**Closed by Kpudlo** 2023-12-26 23:26 UTC
Labels: enhancement
