### ISSUE TITLE
Add CSS classes that don't get added to the selectors list

### ISSUE THREAD

**Issue by opjustin** [soflyy/oxygen-bugs-and-features#1901] opened 2021-02-10 09:37 UTC
It would be great if there was an Additional Classes field where we could put classes in that don't get added to the selectors list.

I know this would also mean not being able to style in the properties pane but would allow us to use external scripts and styles without adding to a long list of selectors. 

Maybe it could be in the custom CSS item above the style text area.

An example would be when looking for CSS classes with jQuery I want to be able to find a group of them. I don't need the class to be anything other than identifier for my script.

**Comment by Kpudlo** [comment] 2023-04-28 12:42
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/76

**Closed by Kpudlo** 2023-04-28 12:42 UTC
Labels: enhancement, Oxygen - Selectors/Stylesheets/Classes
