### ISSUE TITLE
Gutenberg's alignment options on Oxygen's Gutenberg Blocks

### ISSUE THREAD

**Issue by fredb8x** [soflyy/oxygen-bugs-and-features#3193] opened 2023-01-11 08:37 UTC
All is in the title,
It would be nice to have the traditionnal alignment options on Oxygen's Gutenberg Blocks.

It's difficult today to customize Oxygen's Gutenberg Blocks without multiply instance of the block.

**Comment by Kpudlo** [comment] 2023-08-18 22:08
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/743

**Closed** 2023-08-18 22:08 UTC
Labels: duplicate
