### ISSUE TITLE
Link pages by ID an not by URL

### ISSUE THREAD

**Issue by bohdanps** [soflyy/oxygen-bugs-and-features#3308] opened 2023-05-23 08:06 UTC
**Describe the feature you'd like to see included in Oxygen.**
When you use any link component (text link, link wrapper) and link it to a internal page, it's using using page's plain URL:

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/29403400/6834b150-4217-4abe-943d-8e6eddfd0b31)

But if you change that URL in the future, the linked URL won't update automatically and it will result in broken pages and extra work of changing those links manually.

For example if i link Contact page in 10 different pages and then change contact page slug, I'll have to go to 10 pages and re-link Contact page. Or create a redirection, which is faster but not perfect for performance.

Wouldn't it be better to link pages using their ID? This way page will always be linked and you will avoid 404 errors or innecesary redirections.

Right now im using this workaround and it would be very nice to have it by default:

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/29403400/df3bf3af-5ba0-4e33-8cbf-73f3e89526f4)

Or maybe an ID option like you already do with images:

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/29403400/01638a98-7f54-4856-83a0-4fb85d5d7dd1)

**Comment by Kpudlo** [comment] 2023-06-28 11:10
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1231

**Closed by Kpudlo** 2023-06-28 11:10 UTC
Labels: enhancement
