### ISSUE TITLE
Oxygen blocks : if a image is inside a link you can't change the image in Gutenberg

### ISSUE THREAD

**Issue by controlauk** [soflyy/oxygen-bugs-and-features#3202] opened 2023-01-20 13:52 UTC
**Describe the bug**
Oxygen blocks : if a image is inside a link wrapper you can't change the image in Gutenberg

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
(https://oxygen-q3bav75m57sql.oxygen-demo.qsandbox.org/)

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. create a oxegen block
2. put a link wrapper 
3. put a image inside the link wrapper
4. save 
5. add the new block to any page  / post in Gutenberg
6. try and change the image url, you cant

Please fix this important bug as this is important for using blocks

**Comment by Kpudlo** [comment] 2023-01-25 21:10
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/725

**Closed by Kpudlo** 2023-01-25 21:10 UTC
Labels: bug
