### ISSUE TITLE
Taxonomy ACF field dynamic data doesn't populate on archive w/posts assigned

### ISSUE THREAD

**Issue by wallenstone** [soflyy/oxygen-bugs-and-features#3335] opened 2023-06-13 20:16 UTC
**Describe the bug**
ACF fields on taxonomy term archives only populate via dynamic data if no posts are assigned to the term

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qh6k3armyjxsl.oxygen-demo.qsandbox.org/product-type/sound-panels/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create CPT and taxonomy using ACF plugin
2. Add custom field to taxonomy via ACF
3. Create taxonomy term and populate custom field
4. Create Oxygen template for archive
5. Populate text via Oxygen dynamic data insertion
6. See that it populates properly
7. Add a post to the term
8. See that the data does not populate now

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment] 2023-07-19 02:53
Duplicate of https://github.com/soflyy/oxygen/issues/2832

**Closed by Kpudlo** 2023-07-19 02:53 UTC
Labels: duplicate
