### ISSUE TITLE
One Button to Resign all Shortcodes

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#2754] opened 2022-02-18 08:22 UTC
While we still have to resign Shortcodes, can we please have one button to resign all Shortcodes?
![SIGNSHORTCODES](https://user-images.githubusercontent.com/12590359/154644796-a636dd4d-fa33-4bea-9fe3-564c4633b9bf.jpg)

it's a pain to have to manually check 15 + checkboxes to resign all shortcodes. We don't even have a check-all box.

**Comment by d19dotca** [comment] 2022-02-20 19:07
This appears to be a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2103 filed originally.

**Comment by KittenCodes** [comment] 2022-02-22 08:16
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2608. Closing this out.

**Closed by KittenCodes** 2022-02-22 08:16 UTC
Labels: enhancement
