### ISSUE TITLE
Column's default padding cannot be overridden via class

### ISSUE THREAD

**Issue by kaibrockelt** [soflyy/oxygen-bugs-and-features#3482] opened 2024-01-06 13:24 UTC
**Describe the bug**
When creating a "columns" node, it comes with hard coded padding values of 20px on each of it's child divs.  This CSS rule however is so strict, (classname > classname) so that you won't be able to override it with a class on your own. As a result, these rules only can be overridden via ID or custom CSS using "!important". 

could you:
* either make the rule less specific, so a class can override it
* or remove the defaults
* or set the defaults via UI, not via hard background CSS rule

in any case, this is not a showstopper, but getting the padding set requires more complexity than needed, ultimately leading to unclean code rules or ugly overrides. Fixing this would drive simplicity and tidyness.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-q6h5qgsl9958.oxygen-demo.qsandbox.org/lorem-paddingum/

**Comment by Kpudlo** [comment] 2024-01-16 02:41
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1802

**Closed by Kpudlo** 2024-01-16 02:41 UTC
Labels: bug
