### ISSUE TITLE
Query Users

### ISSUE THREAD

**Issue by OJGaming** [soflyy/oxygen-bugs-and-features#2860] opened 2022-05-06 21:03 UTC
I'd like to see the ability to query users in repeaters instead of just posts. Elementor can do this, but I can't figure out how to do it in Oxygen.

You could show a list of users based on role, status, etc.

**Comment by portseif** [comment] 2022-05-09 17:12
+1

**Comment by Kpudlo** [comment] 2024-04-01 11:45
Closing as duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2257

**Closed by Kpudlo** 2024-04-01 11:45 UTC
Labels: enhancement
