### ISSUE TITLE
Allow to edit background images to Div using Gutenberg

### ISSUE THREAD

**Issue by jantivola** [soflyy/oxygen-bugs-and-features#2337] opened 2021-08-09 14:24 UTC
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
At the moment, you can only edit background images on Sections if you are to create a Gutenberg block. Adding an option to edit background images added on "Div" would be a great enhancement especially if you are implementing a full-width section and only want to show a background image on a "Div" within it, hence it will only show the background image on content width. (I hope that make sense)

**Comment by damdam083** [comment] 2022-11-07 03:29
I just found a trick for this one! 
It's not ideal semantically though but while waiting for Oxygen to give us the functionality you can :
- select the div
- in the primary panel, on the last option called "Tag", change it to "section". 
- Then you will have the possibility to change the image from the Gutenberg block.

**Comment by Kpudlo** [comment] 2023-02-23 13:28
Closing as duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1922

**Closed by Kpudlo** 2023-02-23 13:28 UTC
Labels: enhancement, Integration - Gutenberg, Element - Section/Div/Columns
