### ISSUE TITLE
Set Default Unit (other than pixel)

### ISSUE THREAD

**Issue by Dinophox** [soflyy/oxygen-bugs-and-features#2898] opened 2022-05-28 07:24 UTC
**Describe the feature you'd like to see included in Oxygen.**
This feature should allow us to set a different UI unit other than pixels by default. Because accessibility now is an issue and switching constantly into rem/em unit takes time over a week developing the website. Other tools have this on their roadmap and will be a game changer. 

**What are the use cases for this feature?**
Accessibility, faster development times, better UX

**Examples of this feature or functionality.**
In the global settings, I would let people choose the default unit in rem/em or anything really. 
When changing the padding, I would only insert the number instead of selecting the unit and the number.

**Comment by Kpudlo** [comment] 2022-07-12 19:05
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2121

**Closed by Kpudlo** 2022-07-12 19:05 UTC
Labels: enhancement
