### ISSUE TITLE
Drag, drop, copy/paste elements inside the "Structure" panel

### ISSUE THREAD

**Issue by ssim086** [soflyy/oxygen-bugs-and-features#1850] opened 2021-01-14 21:32 UTC
**Describe the feature you'd like to see included in Oxygen.**
It would be super helpful to move elements around within the "Structure" panel instead of just dragging them around on the canvas. 

**What are the use cases for this feature?**
It's difficult to target the parent element when trying to drag things around in the editor. The "Structure" panel would be nice to have the finite control over where elements can be placed or combined.

**Examples of this feature or functionality.**
Webflow does this well. I can drag elements around using the tree panel just as I would in a code editor. Being able to copy and paste groups of elements from one container or div into another would be awesome as well.

**Webflow example:** https://www.loom.com/share/66aef791a16f4764bcf2a60397ecfbde
**Oxygen example:** https://www.loom.com/share/ad7b88fde7624ebbae7e79bc0570d34f

**Comment by trudoom** [comment] 2021-01-14 22:59
Looks like the same task #1845 two days ago...

**Comment by Kpudlo** [comment] 2023-04-12 13:59
Duplicate of #1845

**Closed by Kpudlo** 2023-04-12 13:59 UTC
