### ISSUE TITLE
Access the Oxy Selectors from WP Dashboard

### ISSUE THREAD

**Issue by MimiDev** [soflyy/oxygen-bugs-and-features#3055] opened 2022-08-13 11:03 UTC
**Enable access to the Selectors from WP Dashboard.**
It would be so very handy to access the Oxy Selectors from the WP Dashboard without having to load an Oxy Builder session. Sometimes all I need to do is a small adjustment to some classes, but to do it, I have to open a page/template in Oxy Builder. 

Use cases: pretty much every single site I've built and will build in the future.

**Comment by Kpudlo** [comment] 2022-08-18 20:16
Duplicate of [#64](https://github.com/soflyy/oxygen-bugs-and-features/issues/644)

**Closed by Kpudlo** 2022-08-18 20:16 UTC
Labels: enhancement
