### ISSUE TITLE
Add dynamic data feature to Oxygen Testimonial Helper

### ISSUE THREAD

**Issue by AnthonyBrowneCreative** [soflyy/oxygen-bugs-and-features#3326] opened 2023-06-06 15:30 UTC
I've been using the Oxygen Testimonial Helper in a couple of client projects and I think it works well. However, I have just hit a major blocker in a new project where the testimonial needs to be dynamic. I want to pull the author's image, quote and author info from a custom post type using a dynamic repeater so that the testimonials can be rapidly altered. Yet, there is currently no way to convert the text to dynamic fields (like you can with regular headings and text blocks).

Please can you add this feature? In the meantime, I'm going to rebuild my testimonial card the old-fashioned way so that I have complete control.

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/74543030/0e5e25d9-1719-4f52-a846-09fcb33e9619)

Thanks.

Kind regards

Anthony

**Comment by Kpudlo** [comment] 2023-07-19 02:41
duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2258

**Closed by Kpudlo** 2023-07-19 02:41 UTC
Labels: duplicate
