### ISSUE TITLE
Add icon in button widget

### ISSUE THREAD

**Issue by MaximeStarssed** [soflyy/oxygen-bugs-and-features#3264] opened 2023-03-10 17:01 UTC
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
Hello, in order to customize my buttons more easily, I would like to add icons directly.

This would avoid having to use the Link Wrapper widget with an icon inside.
**What are the use cases for this feature?**
Website production in Oxygen Builder

Thank you

**Comment by Kpudlo** [comment] 2023-03-30 14:03
duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/773

**Closed by Kpudlo** 2023-03-30 14:03 UTC
Labels: duplicate, enhancement
