### ISSUE TITLE
Full Standalone Theme Export

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#1256] opened 2020-06-14 18:20 UTC
It would be really cool if I could create a website design with this Oxygen Builder, and then be able to export my design as a standalone WordPress theme that can then be installed on my clients website. The theme package will contain all the necessary CSS/JS to make it work, without having the Oxygen builder plugin installed.

This feature could facilitate custom theme building, and also looks more professional to the client, as they are getting a custom theme, and not an end product that can be confused with an unprofessional page builder.

This feature would have the ability to export a full WordPress theme along with all the required files to make it run. It will also need to have version control so we can update the installed theme easily.

**Comment by Kpudlo** [comment] 2023-07-19 16:10
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2994

**Closed by Kpudlo** 2023-07-19 16:10 UTC
Labels: enhancement, Oxygen - Export/Import
