### ISSUE TITLE
Place Oxygen CSS at the top of the <head> - Improve CWV and page loading.

### ISSUE THREAD

**Issue by MaximeStarssed** [soflyy/oxygen-bugs-and-features#3468] opened 2023-12-13 10:48 UTC
**Describe the feature you'd like to see included in Oxygen.**

**CSS files (generated by Oxygen) have a blocking rendering**: i.e. the page cannot be displayed until they are loaded.

You can check this at https://www.webpagetest.org.

Unfortunately, they're only loaded at the end of the `<head>`, i.e. after the other codes like social networks, favicons, Woocommerce deferred JS, etc.

**Solution: CSS codes should be loaded first in the `<head>`, not last.**

**What are the use cases for this feature?**
Improve Core Web Vital and page loading by loading Oxygen CSS codes first.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
Oxygen could easily increase the priority of its CSS files in the `<head>`, as it has already done with typekit codes.

**Comment by Kpudlo** [comment] 2023-12-26 22:26
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3468

**Closed by Kpudlo** 2023-12-26 22:26 UTC
Labels: enhancement
