### ISSUE TITLE
"This design contains elements regitered by another plugin that is no longer active."

### ISSUE THREAD

**Issue by LeSill** [soflyy/oxygen-bugs-and-features#3513] opened 2024-03-04 07:45 UTC
Hello, everyone.
Oxygen error report:
_This design contains elements registered by another plugin that is no longer active. Please re-activate the appropriate plugins or remove the missing elements before saving._
![error report](https://github.com/soflyy/oxygen-bugs-and-features/assets/29061312/90ac0d41-4363-404e-94df-cce2bf278fa2)

I've had this issue multiple times in the last several days. This problem has been mentioned on the Oxygen Facebook group for several months, but no one has worked out what is causing it. I don't have any plugins missing; everything is enabled. I've observed a certain pattern. When I work on a template layout for tablet, smartphone, and other devices and then move on to a page, the problem arises regularly. I can't save my page then.
Steps before getting the error:
1. Select the footer template / full-screen layout.
2. Make some modifications to the layout and save them.
3. Switch to the tablet layout, make modifications, and save.
4. Open a page (a work page in my instance), review the design, and then return to the footer template.
5. Make some adjustments to the footer template / tablet layout and save it.
6. Switch to mobile layout and make some changes to the footer template. Save it.
7. Go to a page (my work page) / TRY TO SAVE IT, AND THE PROBLEM OCCURS.

This mistake is a HUGE PROBLEM. It appears at random and frequently, and every time it does, I am unable to save my work, resulting in complete loss of data. Have you figured out how to avoid this?

**Comment by Kpudlo** [comment] 2024-03-04 12:48
Duplicate of #3108 

Hello @LeSill, 

Please open a Support Ticket (https://oxygenbuilder.com/support) with the requested information to see the issue on your site. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.

**Closed by Kpudlo** 2024-03-04 12:48 UTC
Labels: bug
