### ISSUE TITLE
Errors 4.0 Alpha - WPGridBuilder Oxygen Add-on

### ISSUE THREAD

**Issue by astacreative** [soflyy/oxygen-bugs-and-features#2595] opened 2021-12-27 19:10 UTC
Immediately after activation (and cleared cache and Shortcode Signing):

WPGridBuilder with Oxygen add-on (without this add-on the error isn't displayed) error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Grid_Builder_Oxygen\Includes\Observer::render(), 2 passed in /home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-includes/class-wp-hook.php on line 303 and exactly 3 expected in /home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-content/plugins/wp-grid-builder-oxygen/includes/class-observer.php:72 Stack trace: #0 /home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-includes/class-wp-hook.php(303): WP_Grid_Builder_Oxygen\Includes\Observer->render('<div id="_heade...', 'oxy_header_left') #1 /home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-includes/plugin.php(189): WP_Hook->apply_filters('<div id="_heade...', Array) #2 /home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-content/plugins/oxygen/component-framework/includes/templates.php(66): apply_filters('do_shortcode_ta...', '<div id="_heade...', 'oxy_header_left') #3 /home/u39485p34917/domains/xxx.dev/public_h in
/home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-content/plugins/wp-grid-builder-oxygen/includes/class-observer.php
on line
72

**Comment by madjedo** [comment] 2021-12-28 12:08
I can confirm this aswell on my 4.0 site aswell.

**Comment by adrien-robert** [comment] 2021-12-28 16:04
+1

**Comment by Spellhammer** [comment] 2021-12-28 16:38
This looks like something WP GridBuilder will have to fix on their end, please be sure to report it to them as well.

**Comment by astacreative** [comment] 2021-12-28 16:43
@Spellhammer I sent this WP GridBuilder as well. Their response was:

We do not provide support for alpha or beta version of plugins/themes.
Once the plugin will have a stable version and if there is still an error, we will take a look at it.
Thank you for your understanding.

**Comment by Spellhammer** [comment] 2021-12-28 17:08
That's a pretty weird response. You would think they would want their plugin to not break on all Oxygen sites when the RC/final is released. We also plan to reach out to them and other third-party add-on/integration providers leading up to release so that they have a chance to make any changes or corrections.

**Comment by loicblascos** [comment] 2021-12-29 09:48
Hi there!

I am the author of WP Grid Builder.
This error is not related to WP Grid Builder but to Oxygen 4.0 Alpha 1 version.

Oxygen applies a WordPress PHP filter without passing all the arguments required by WordPress...
Currently, 2 arguments are missing from the Oxygen code when applying this PHP filter.
Thus, this error will be triggered by any plugin using more than 2 arguments with the PHP Hook: `do_shortcode_tag`.
Here is the line (mentioned in the error message of this issue) that causes the error (`/oxygen/component-framework/includes/templates.php` line 66):

`$html = apply_filters( 'do_shortcode_tag', $html, $tag); // JSON TODO: two arguments more to add to filter.`

As alpha versions can create false positives with other plugins, we only fully test from a more stable version.
And, if necessary, we always fix problems before the official release, of course.

**Comment by Spellhammer** [comment] 2021-12-29 15:08
@loicblascos Thanks for weighing in, we'll investigate on our end.

**Comment by Brandinwebdesign** [comment] 2022-01-18 13:07
> @Spellhammer I sent this WP GridBuilder as well. Their response was:
> 
> We do not provide support for alpha or beta version of plugins/themes. Once the plugin will have a stable version and if there is still an error, we will take a look at it. Thank you for your understanding.

I have send them also a ticket. I got the same reaction...

**Comment by sc0ttkclark** [comment] 2022-02-07 05:08
Definitely do not run core hooks without passing all arguments those hooks are documented to pass. Thanks for reopening this.

Core usage you should use for reference:

```php
	/**
	 * Filters the output created by a shortcode callback.
	 *
	 * @since 4.7.0
	 *
	 * @param string       $output Shortcode output.
	 * @param string       $tag    Shortcode name.
	 * @param array|string $attr   Shortcode attributes array or empty string.
	 * @param array        $m      Regular expression match array.
	 */
	return apply_filters( 'do_shortcode_tag', $output, $tag, $attr, $m );
```

**Comment by KittenCodes** [comment] 2022-02-10 09:06
This should be fixed in v4 Beta 1.

**Closed by KittenCodes** 2022-02-10 09:06 UTC
Labels: bug

**Comment by loicblascos** [comment] 2022-02-10 09:19
To avoid any compatibility issues in Oxygen v4 Beta 1, if you use `do_shortcode_tag` to replicate WordPress shortcodes, don't forget to also add the `pre_do_shortcode_tag` filter to fully simulate shortcode feature, as many plugins also rely on this PHP filter (to conditionally render shortcodes for example).

**Comment by loicblascos** [comment] 2022-02-22 20:37
Since Oxygen 4.0 beta 1, WordPress PHP filters are applied with the right number of arguments.

However the first argument `$output` (`$html` in Oxygen code) used in `do_shortcode_tag` filter is not correct. It should pass the output of the shortcode but it doesn't because of the concatenation of the output that takes place earlier in the Oxygen code. Therefore, if a plugin modifies the output of the shortcode it may also affect the previous ones and lead to an unexpected result in the context of Oxygen.

The last argument of the filters `pre_do_shortcode_tag` and `do_shortcode_tag` corresponding to the regular expression matching array always passes an empty array.

All this will always lead to unwanted behavior in Oxygen. If the behavior of WordPress is not fully satisfied it will never work properly...

**Comment by KittenCodes** [comment] 2022-02-22 20:49
Thanks @loicblascos - I've reported this internally.

**Comment by wplit** [comment] 2022-02-28 01:16
@loicblascos 

You're likely already aware, but on the off chance it was missed thought I'd mention it. Currently the facets when used with Oxygen's repeater in the v4 beta isn't adding the posts inside of the repeater, but instead inside the facet div.

https://www.loom.com/share/02887c1d0f2545f19d07e14a73a7af47

**Comment by loicblascos** [comment] 2022-03-06 07:26
@wplit 

Yes, I know about it. This is because of the misuse of WordPress PHP filters from Oxygen v4 Beta.
This is what I explained in my previous reply. Oxygen v4 beta applies the filter on the whole content and not only on the shortcode output. As a result, it mixes content of the page (actually mainly nested shortcodes). This has an impact on the page rendering but also on the performance.

**Comment by barrychapman** [comment] 2022-06-02 05:05
@loicblascos 

When selecting a facet from the archive page that has the facets on it, our responses come back with garbled data:

https://user-images.githubusercontent.com/152958/171556677-cc514228-eb43-4cf9-874c-cb8ecc23139a.mp4

Any idea why this happens?
