### ISSUE TITLE
Stylesheet Loading Conditions 

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#3178] opened 2023-01-02 17:46 UTC
Currently, stylesheets load everywhere, even in places they are not needed. With a Stylesheet Loading Conditions feature we can choose which page, post, cpt, etc to load them on, thereby saving resources.

**Comment by Kpudlo** [comment] 2023-01-25 21:30
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/18

**Closed by Kpudlo** 2023-01-25 21:30 UTC
Labels: enhancement
