### ISSUE TITLE
HTML Header Truncated

### ISSUE THREAD

**Issue by KeanuTang** [soflyy/oxygen-bugs-and-features#3316] opened 2023-05-31 14:00 UTC
https://oxygen-qaj44hggdqqsl.oxygen-demo.qsandbox.org/
Go to the sandbox and view the source. You'll see that the header is truncated and missing a lot of the necessary css/js. 

![oxygen bug 1](https://github.com/soflyy/oxygen-bugs-and-features/assets/121991155/e83c6400-3d8a-46e0-abf7-23617e8ae10d)
![oxygen bug 2](https://github.com/soflyy/oxygen-bugs-and-features/assets/121991155/1114c39b-3f9a-4733-8e8c-e2571701c63a)

Steps to reproduce on sandbox:
1. Create a brand new sandbox site. Choose to create a blank website.
2. View source of the homepage. You'll see it's truncated. 

How this poses a problem:
I am trying to leverage the Oxygen-Gutenberg integration, where I can create Gutenberg blocks from Oxygen elements. That process seems to work just fine. I am able to select an Oxygen element and convert it to a block that appears usable in Gutenberg. However, when I go to build a Gutenberg page using this block, the resulting page renders in a broken way because it is missing its css/js. This is most definitely a bug! Please don't just close this bug or tell me "go build the page in Oxygen." The whole point of this integration is that we should be able to build the page in Gutenberg. 

I am posting a new bug report of this issue that was closed: https://github.com/soflyy/oxygen-bugs-and-features/issues/3288

**Comment by Kpudlo** [comment] 2023-05-31 14:31
Closing as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3288. 

If we find there is an issue after further investigation, we'll re-open #3288

**Closed by Kpudlo** 2023-05-31 14:31 UTC
