### ISSUE TITLE
Maintenance Mode logic that doesn't require conditionals

### ISSUE THREAD

**Issue by keyinora** [soflyy/oxygen-bugs-and-features#3195] opened 2023-01-12 22:24 UTC
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

I know your team created a tutorial using conditionals, but I'd like to request a feature that is very much like OxyPowerPack (which currently appears to have been abandoned).

This feature would allow you to turn on the maintenance mode globally, provide a bypass URL, and also have a page that users will be redirected to when they don't have the bypass URL.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

When an issue crops up, or when you need to close the site for whatever reason, but you don't have a lot of time.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
OxyPowerPack

**Comment by Kpudlo** [comment] 2023-01-13 18:27
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2298

**Closed by Kpudlo** 2023-01-13 18:27 UTC
Labels: enhancement
