### ISSUE TITLE
Integration with Pods - Custom Content Types and Fields

### ISSUE THREAD

**Issue by designbydart** [soflyy/oxygen-bugs-and-features#3289] opened 2023-04-27 12:33 UTC
Hi,

is it possible to support the Pods - Custom Content Types and Fields plugin, and more precisely to include the dynamic data function in the gallery (there is already support for AFC and Metabox)

**Comment by Kpudlo** [comment] 2023-04-27 13:42
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2122

**Closed as completed by Kpudlo** 2023-04-27 13:42 UTC
Labels: enhancement
