### ISSUE TITLE
Layout->Display:None not working when Section height is set to value

### ISSUE THREAD

**Issue by visionlabit** [soflyy/oxygen-bugs-and-features#3076] opened 2022-09-08 08:43 UTC
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
When a Section element is added and its height is set to a specific value (e.g. height=100vh) it is impossible to hide it using Layout->Display: None  (as suggested in  https://oxygenbuilder.com/documentation/visual-editing/responsive-controls/)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Add a Section element to the page
2. Set its height to 100vh
3. Set its Display property under Layout settings to 'None'
4. See the section is still visible on the page

![Screenshot 2022-09-08 104101](https://user-images.githubusercontent.com/100320945/189077411-7d1ec6e5-db5a-420a-9c24-2873e47e9fee.png)

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment] 2022-09-08 20:03
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2462

**Closed by Kpudlo** 2022-09-08 20:03 UTC
Labels: bug
