### ISSUE TITLE
Add native lazy loading by default, loading=lazy tag 

### ISSUE THREAD

**Issue by yoshi-12321** [soflyy/oxygen-bugs-and-features#2049] opened 2021-03-27 13:20 UTC
please add native lazy loading for Images by adding the loading = lazy tag for „img„ by default.
Right now it can be added manually for each image individually only, via custom tag.
-Thx in advance

**Comment by alpabuz** [comment] 2021-04-04 16:02
@KittenCodes I suppose a duplicate request. Originally stuck here for a long time: https://github.com/soflyy/oxygen-bugs-and-features/issues/995

Solution for newbies or those who just didn't know about it (and those who will read this for the first time): https://oxywp.com/enable-for-native-lazy-loading-images-for-the-image-element-in-oxygen/

**Comment by KittenCodes** [comment] 2021-04-05 18:34
@alpabuz 

> I suppose a duplicate request. Originally stuck here for a long time: #995

Correct - this is a duplicate of #995.

**Closed by KittenCodes** 2021-04-05 18:34 UTC
Labels: Element - Image, General - Performance/Optimisation - Lazy Loading, enhancement
