### ISSUE TITLE
What's the deal with all the opinionated styles in `woo-global-styler.css`?

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#3437] opened 2023-11-04 01:16 UTC
Forcing a `letter-spacing` on buttons and other odd / opinionated woo styles is a pain.

It would handy if oxygen provided a way to prevent these styles from being added to `universal.css` so we don't need to override this css pollution. 

🚀

**Comment by Kpudlo** [comment] 2023-12-01 13:24
Marking as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3221 since adding a filter would resolve this.

**Closed by Kpudlo** 2023-12-01 13:24 UTC
Labels: enhancement

**Comment by perrelet** [comment] 2024-03-27 22:46
https://github.com/soflyy/oxygen-bugs-and-features/issues/3221#issuecomment-2024110807
