### ISSUE TITLE
Metabox Single Image in Group can't be displayed in Oxygen repeater

### ISSUE THREAD

**Issue by cheneycha** [soflyy/oxygen-bugs-and-features#3423] opened 2023-10-17 11:57 UTC
When using Metabox: Single Image inside of cloneable Group, the Oxygen repeater>image element>image url calls the image id which is incorrect, leads to the image not displayed in the Oxygen repeater.
Here is the sandbox link https://oxygen-qwa36mfbkprvl.oxygen-demo.qsandbox.org/test/

There is a Metabox group associated with this test page, including a Single Image and a Text field. 

The Metabox document of getting Single Image url in Group for reference.
https://docs.metabox.io/extensions/meta-box-group/#sub-field-values

**Comment by wheeleran** [comment] 2023-11-26 16:10
You can use image_advanced, but that leads you to the other bug, which was first reported and confirmed two years ago and is still not fixed: all image_advanced images are rendered correctly on the front end, but only at 150x150px thumbnail size, and outputs only error code and no image in the Builder. I've just been through this with Oxy Support last week so don't waste your time. The workaround is to use a code block, with:

```
global $meta_box_current_group_fields;
$image_src = wp_get_attachment_image_src($meta_box_current_group_fields['tool_image'][0], "full")[0];
?>
<img class="mb-image_img" src="<?= $image_src;?>">

```

where 'tool_image' is the ID of your Group image custom field.

Apparently the code block for a single image field is:

```
global $meta_box_current_group_fields;
$image_src = wp_get_attachment_image_src($meta_box_current_group_fields['tool_image'], "full")[0];
?>
<img class="mb-image__img" src="<?= $image_src;?>">
```

But I haven't tested it. The css for both is:

```
.mb-image {
width: 100%;
}
.mb-image > .mb-image_img {
width: 100%;
height: 100%;
object-fit: cover;
}
```

And if ANYONE has a better solution, please, we'd love to hear it...

**Comment by arsh999cg** [comment] 2023-11-26 20:32
Regarding the above @wheeleran solution :
The first code-block will work for meta box single image field inside a cloneable MB group in Oxygen,

Another way is to make a PHP return function, just to save time when you want to fetch the single image multiple times or multiple images...

```php
function arsh_image_subfield_cloneable($field_id, $size = 'full') {
    global $meta_box_current_group_fields;
    return wp_get_attachment_image_src($meta_box_current_group_fields[$field_id][0], $size)[0];
}
// Now call it as php return function arsh_image_subfield_cloneable and parameter, "field_id,size" as single_image_2,full etc.
```


put the above code in a code-snippet of your choice, Scripts Organizer, Code Snippets Pro, WPCodebox etc, and use it inside Oxygen Metabox Group repeater via Inserting Image and change to IMAGE URL and use dynamic data with PHP return function :

function name : arsh_image_subfield_cloneable
arguments : your requried size (i.e.     full, thumbnail, medium, custom_size    etc...)

**Comment by wheeleran** [comment] 2023-11-26 20:41
Hey @arsh999cg very cool, thanks!

**Comment by Kpudlo** [comment] 2023-12-26 21:29
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2546

**Closed by Kpudlo** 2023-12-26 21:29 UTC
Labels: bug
